// packages/core/src/workshop/features/createCanvas/CreateCanvasForm.svelte
<!--
  CreateCanvasForm — workshop form for creating a new canvas.
  Uses shadcn-svelte components for all form elements.
-->

<script lang="ts">
  import { onMount } from 'svelte'
  import { Button } from '../../../lib/components/ui/button/index.js'
  import { Input } from '../../../lib/components/ui/input/index.js'
  import { Label } from '../../../lib/components/ui/label/index.js'
  import { Checkbox } from '../../../lib/components/ui/checkbox/index.js'
  import * as Panel from '../../../lib/components/ui/panel/index.js'
  import * as Alert from '../../../lib/components/ui/alert/index.js'

  interface Props { onClose?: () => void }
  let { onClose }: Props = $props()

  let name = $state('')
  let title = $state('')
  let titleTouched = $state(false)
  let folder = $state('')
  let includeJsx = $state(false)
  let grid = $state(true)

  let folders: string[] = $state([])
  let loading = $state(true)
  let submitting = $state(false)
  let error: string | null = $state(null)
  let success: string | null = $state(null)
  let createdRoute: string | null = $state(null)

  const kebabName = $derived(
    name.replace(/[^a-zA-Z0-9\s_-]/g, '').trim().replace(/[\s_]+/g, '-').toLowerCase().replace(/-+/g, '-').replace(/^-|-$/g, '')
  )
  const autoTitle = $derived(
    kebabName ? kebabName.split('-').map((s: string) => s.charAt(0).toUpperCase() + s.slice(1)).join(' ') : ''
  )
  const displayTitle = $derived(titleTouched ? title : autoTitle)
  const routePreview = $derived(kebabName ? `/canvas/${kebabName}` : '')
  const nameError = $derived(
    name.trim() && !kebabName ? 'Name must contain at least one alphanumeric character'
    : name.trim() && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(kebabName) ? 'Name must be kebab-case'
    : null
  )
  const canSubmit = $derived(!!kebabName && !nameError && !submitting)

  function getApiUrl() {
    const basePath = window.__STORYBOARD_BASE_PATH__ || '/'
    return basePath.replace(/\/$/, '') + '/_storyboard/canvas'
  }

  const CANVAS_SUCCESS_KEY = 'sb-canvas-created'

  onMount(async () => {
    // Restore success state after Vite's full-reload on file creation
    try {
      const saved = sessionStorage.getItem(CANVAS_SUCCESS_KEY)
      if (saved) {
        const parsed = JSON.parse(saved)
        success = parsed.success
        createdRoute = parsed.route
        sessionStorage.removeItem(CANVAS_SUCCESS_KEY)
      }
    } catch {}

    try {
      const res = await fetch(getApiUrl() + '/folders')
      if (res.ok) {
        const data = await res.json()
        folders = data.folders || []
      }
    } catch { /* defaults */ } finally { loading = false }
  })

  function handleTitleInput(e: Event) { title = (e.target as HTMLInputElement).value; titleTouched = true }
  function handleTitleBlur() { if (!title.trim()) titleTouched = false }

  async function submit() {
    if (!canSubmit) return
    submitting = true; error = null; success = null; createdRoute = null
    try {
      const res = await fetch(getApiUrl() + '/create', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: kebabName, title: displayTitle, folder: folder || undefined, grid, includeJsx }),
      })
      const data = await res.json()
      if (!res.ok) { error = data.error || 'Failed to create canvas'; return }
      success = `Created ${data.path}`
      createdRoute = data.route
      // Persist success state — Vite does a full-reload when new files are created
      try {
        sessionStorage.setItem(CANVAS_SUCCESS_KEY, JSON.stringify({ success, route: createdRoute }))
      } catch {}
    } catch (err: any) { error = err.message || 'Network error' } finally { submitting = false }
  }

  function handleKeydown(e: KeyboardEvent) { if (e.key === 'Enter' && canSubmit) submit() }
</script>

<Panel.Header>
  <Panel.Title>Create canvas</Panel.Title>
  <Panel.Close />
</Panel.Header>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="p-4 pt-2 space-y-3" onkeydown={handleKeydown}>
  <div class="space-y-1">
    <Label for="sb-canvas-name">Name</Label>
    <Input id="sb-canvas-name" placeholder="e.g. design-overview" autocomplete="off" spellcheck="false" bind:value={name} />
    {#if nameError}<p class="text-sm text-destructive">{nameError}</p>{/if}
    {#if routePreview}<p class="text-xs text-muted-foreground">Route: <code class="px-1 py-0.5 bg-muted rounded font-mono text-foreground text-xs">{routePreview}</code></p>{/if}
  </div>

  <div class="space-y-1">
    <Label for="sb-canvas-title">Title</Label>
    <Input id="sb-canvas-title" placeholder={autoTitle || 'Auto-derived from name'} value={displayTitle} oninput={handleTitleInput} onblur={handleTitleBlur} />
  </div>

  <div class="space-y-1">
    <Label for="sb-canvas-folder">Folder</Label>
    <select class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-xs transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50" id="sb-canvas-folder" bind:value={folder} disabled={loading}>
      <option value="">None</option>
      {#each folders as f}<option value={f}>{f}</option>{/each}
    </select>
  </div>

  <div class="flex items-center gap-2">
    <Checkbox id="sb-canvas-grid" bind:checked={grid} />
    <Label for="sb-canvas-grid" class="text-sm font-normal cursor-pointer">Show grid</Label>
  </div>

  <div class="flex items-center gap-2">
    <Checkbox id="sb-canvas-jsx" bind:checked={includeJsx} />
    <Label for="sb-canvas-jsx" class="text-sm font-normal cursor-pointer">Include JSX companion file</Label>
  </div>

  {#if error}<Alert.Root variant="destructive"><Alert.Description>{error}</Alert.Description></Alert.Root>{/if}
  {#if success}<Alert.Root><Alert.Description class="text-success">{success}{#if createdRoute} — <a href={createdRoute} class="underline font-medium">Go to canvas</a>{/if}</Alert.Description></Alert.Root>{/if}
</div>

<Panel.Footer>
  <Button variant="outline" onclick={onClose}>Cancel</Button>
  <Button onclick={submit} disabled={!canSubmit}>{submitting ? 'Creating\u2026' : 'Create'}</Button>
</Panel.Footer>

// packages/core/src/workshop/features/createCanvas/CreateCanvasForm.jsx
import { useState, useMemo, useEffect } from 'react'
import { Button } from '../../../lib/components/ui/button/index.js'
import { Input } from '../../../lib/components/ui/input/index.js'
import { Label } from '../../../lib/components/ui/label/index.js'
import { Checkbox } from '../../../lib/components/ui/checkbox/index.js'
import * as Panel from '../../../lib/components/ui/panel/index.js'
import * as Alert from '../../../lib/components/ui/alert/index.js'

const CANVAS_SUCCESS_KEY = 'sb-canvas-created'

function getApiUrl() {
  const basePath = window.__STORYBOARD_BASE_PATH__ || '/'
  return basePath.replace(/\/$/, '') + '/_storyboard/canvas'
}

export default function CreateCanvasForm({ onClose }) {
  const [name, setName] = useState('')
  const [title, setTitle] = useState('')
  const [titleTouched, setTitleTouched] = useState(false)
  const [description, setDescription] = useState('')
  const [folder, setFolder] = useState('')
  const [grid, setGrid] = useState(true)
  const [folders, setFolders] = useState([])
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState(null)
  const [success, setSuccess] = useState(null)
  const [createdRoute, setCreatedRoute] = useState(null)

  const kebabName = useMemo(
    () =>
      name
        .replace(/[^a-zA-Z0-9\s_-]/g, '')
        .trim()
        .replace(/[\s_]+/g, '-')
        .toLowerCase()
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, ''),
    [name],
  )

  const autoTitle = useMemo(
    () =>
      kebabName
        ? kebabName
            .split('-')
            .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
            .join(' ')
        : '',
    [kebabName],
  )

  const displayTitle = useMemo(
    () => (titleTouched ? title : autoTitle),
    [titleTouched, title, autoTitle],
  )

  const routePreview = useMemo(
    () => (kebabName ? `/canvas/${kebabName}` : ''),
    [kebabName],
  )

  const nameError = useMemo(() => {
    if (name.trim() && !kebabName)
      return 'Name must contain at least one alphanumeric character'
    if (name.trim() && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(kebabName))
      return 'Name must be kebab-case'
    return null
  }, [name, kebabName])

  const canSubmit = useMemo(
    () => !!kebabName && !nameError && !submitting,
    [kebabName, nameError, submitting],
  )

  useEffect(() => {
    // Restore success state after Vite's full-reload on file creation
    try {
      const saved = sessionStorage.getItem(CANVAS_SUCCESS_KEY)
      if (saved) {
        const parsed = JSON.parse(saved)
        setSuccess(parsed.success)
        setCreatedRoute(parsed.route)
        sessionStorage.removeItem(CANVAS_SUCCESS_KEY)
      }
    } catch {}

    async function fetchFolders() {
      try {
        const res = await fetch(getApiUrl() + '/folders')
        if (res.ok) {
          const data = await res.json()
          setFolders(data.folders || [])
        }
      } catch {} finally {
        setLoading(false)
      }
    }
    fetchFolders()
  }, [])

  function handleTitleInput(e) {
    setTitle(e.target.value)
    setTitleTouched(true)
  }

  function handleTitleBlur() {
    if (!title.trim()) setTitleTouched(false)
  }

  async function submit() {
    if (!canSubmit) return
    setSubmitting(true)
    setError(null)
    setSuccess(null)
    setCreatedRoute(null)
    try {
      const res = await fetch(getApiUrl() + '/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: kebabName,
          title: displayTitle,
          description: description || undefined,
          folder: folder || undefined,
          grid,
        }),
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data.error || 'Failed to create canvas')
        return
      }
      const msg = `Created ${data.path}`
      setSuccess(msg)
      setCreatedRoute(data.route)
      try {
        sessionStorage.setItem(
          CANVAS_SUCCESS_KEY,
          JSON.stringify({ success: msg, route: data.route }),
        )
      } catch {}
    } catch (err) {
      setError(err.message || 'Network error')
    } finally {
      setSubmitting(false)
    }
  }

  function handleKeydown(e) {
    if (e.key === 'Enter' && canSubmit) submit()
  }

  return (
    <div onKeyDown={handleKeydown}>
      <Panel.Header>
        <Panel.Title>Create canvas</Panel.Title>
        <Panel.Close onClick={onClose} />
      </Panel.Header>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', padding: '1rem' }}>
        <div>
          <Label htmlFor="canvas-name">Name</Label>
          <Input
            id="canvas-name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="my-canvas"
          />
          {nameError && (
            <p style={{ color: 'var(--color-danger-fg, red)', fontSize: '0.875rem', marginTop: '0.25rem' }}>
              {nameError}
            </p>
          )}
          {routePreview && (
            <p style={{ color: 'var(--color-fg-muted, #666)', fontSize: '0.875rem', marginTop: '0.25rem' }}>
              {routePreview}
            </p>
          )}
        </div>

        <div>
          <Label htmlFor="canvas-title">Title</Label>
          <Input
            id="canvas-title"
            value={displayTitle}
            onChange={handleTitleInput}
            onBlur={handleTitleBlur}
            placeholder="Auto-generated from name"
          />
        </div>

        <div>
          <Label htmlFor="canvas-description">Description</Label>
          <Input
            id="canvas-description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Optional description"
          />
        </div>

        <div>
          <Label htmlFor="canvas-folder">Folder</Label>
          <select
            id="canvas-folder"
            value={folder}
            onChange={(e) => setFolder(e.target.value)}
            disabled={loading}
          >
            <option value="">No folder</option>
            {folders.map((f) => (
              <option key={f} value={f}>
                {f}
              </option>
            ))}
          </select>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Checkbox
            id="canvas-grid"
            checked={grid}
            onCheckedChange={setGrid}
          />
          <Label htmlFor="canvas-grid">Show grid</Label>
        </div>

        {error && (
          <Alert.Root variant="destructive">
            <Alert.Description>{error}</Alert.Description>
          </Alert.Root>
        )}

        {success && (
          <Alert.Root>
            <Alert.Description>
              {success}
              {createdRoute && (
                <>
                  {' — '}
                  <a href={createdRoute}>Open canvas</a>
                </>
              )}
            </Alert.Description>
          </Alert.Root>
        )}
      </div>

      <Panel.Footer>
        <Button variant="outline" onClick={onClose}>
          Cancel
        </Button>
        <Button onClick={submit} disabled={!canSubmit}>
          {submitting ? 'Creating…' : 'Create'}
        </Button>
      </Panel.Footer>
    </div>
  )
}
