// packages/core/src/CanvasCreateMenu.svelte
<!--
  CanvasCreateMenu — CoreUIBar dropdown for adding widgets to the active canvas.
  Dispatches custom events to bridge Svelte → React.
  Only visible when a canvas page is active.
-->

<script lang="ts">
  import { TriggerButton } from './lib/components/ui/trigger-button/index.js'
  import * as DropdownMenu from './lib/components/ui/dropdown-menu/index.js'
  import { Button } from './lib/components/ui/button/index.js'
  import { Input } from './lib/components/ui/input/index.js'
  import { Label } from './lib/components/ui/label/index.js'
  import Icon from './svelte-plugin-ui/components/Icon.svelte'

  interface Props {
    config?: any
    data?: any
    canvasName?: string
    zoom?: number
    tabindex?: number
  }

  let { config = {}, data, canvasName = '', zoom, tabindex }: Props = $props()

  const widgetTypes = [
    { type: 'sticky-note', label: 'Sticky Note' },
    { type: 'markdown', label: 'Markdown' },
    { type: 'prototype', label: 'Prototype embed' },
  ]

  interface StoryEntry {
    name: string
    path: string
    exports: string[]
  }

  type View = 'menu' | 'create' | 'notification'

  let menuOpen = $state(false)
  let view: View = $state('menu')
  let stories: StoryEntry[] = $state([])
  let storiesLoaded = $state(false)

  // Create form state
  let createName = $state('')
  let createLocation = $state('canvas')
  let createFormat = $state('jsx')
  let submitting = $state(false)
  let createError: string | null = $state(null)
  let notificationPath: string | null = $state(null)

  const kebabName = $derived(
    createName.replace(/[^a-zA-Z0-9\s_-]/g, '').trim().replace(/[\s_]+/g, '-').toLowerCase().replace(/-+/g, '-').replace(/^-|-$/g, '')
  )
  const nameError = $derived(
    createName.trim() && !kebabName ? 'Name must contain at least one alphanumeric character' : null
  )
  const filePreview = $derived(
    kebabName ? `${kebabName}.story.${createFormat}` : ''
  )
  const canSubmit = $derived(!!kebabName && !nameError && !submitting)

  function getApiUrl() {
    const basePath = (window as any).__STORYBOARD_BASE_PATH__ || '/'
    return basePath.replace(/\/$/, '') + '/_storyboard/canvas'
  }

  async function loadStories() {
    try {
      const res = await fetch(getApiUrl() + '/stories')
      if (res.ok) {
        const data = await res.json()
        stories = data.stories || []
      }
    } catch { /* ignore */ }
    storiesLoaded = true
  }

  // Load stories when menu opens
  $effect(() => {
    if (menuOpen) loadStories()
  })

  // Reset view when menu closes
  $effect(() => {
    if (!menuOpen && view !== 'notification') {
      resetCreateForm()
      view = 'menu'
    }
  })

  function resetCreateForm() {
    createName = ''
    createLocation = 'canvas'
    createFormat = 'jsx'
    createError = null
    submitting = false
  }

  function addWidget(type: string) {
    document.dispatchEvent(new CustomEvent('storyboard:canvas:add-widget', {
      detail: { type, canvasName }
    }))
    menuOpen = false
  }

  function addStoryWidget(storyId: string) {
    document.dispatchEvent(new CustomEvent('storyboard:canvas:add-story-widget', {
      detail: { storyId, canvasName }
    }))
    menuOpen = false
  }

  function showCreateForm() {
    resetCreateForm()
    view = 'create'
  }

  async function submitCreate() {
    if (!canSubmit) return
    submitting = true; createError = null
    try {
      const bridgeState = (window as any).__storyboardCanvasBridgeState
      const activeCanvasName = bridgeState?.name || canvasName

      const res = await fetch(getApiUrl() + '/create-story', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: kebabName,
          location: createLocation,
          format: createFormat,
          canvasName: createLocation === 'canvas' ? activeCanvasName : undefined,
        }),
      })
      const data = await res.json()
      if (!res.ok) { createError = data.error || 'Failed to create component'; submitting = false; return }

      // Add the new component to the canvas
      addStoryWidget(data.name)

      // Show inline notification
      notificationPath = data.path
      view = 'notification'
      menuOpen = true

      // Refresh story list for next time
      storiesLoaded = false

      // Auto-dismiss after 6 seconds
      setTimeout(() => {
        if (view === 'notification') {
          menuOpen = false
          view = 'menu'
          notificationPath = null
        }
      }, 6000)
    } catch (err: any) { createError = err.message || 'Network error' } finally { submitting = false }
  }
</script>

<DropdownMenu.Root bind:open={menuOpen} onOpenChange={(open) => {
  if (!open && view === 'notification') {
    view = 'menu'
    notificationPath = null
  }
}}>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <TriggerButton
        active={menuOpen}
        size="icon-xl"
        aria-label={config.ariaLabel || 'Add widget'}
        {tabindex}
        {...props}
      >
        {#if config.icon}
          <Icon name={config.icon} size={16} {...(config.meta || {})} />
        {:else}
          +
        {/if}
      </TriggerButton>
    {/snippet}
  </DropdownMenu.Trigger>

  <DropdownMenu.Content side="top" align="start" sideOffset={16} class="min-w-[180px]" style={config.menuWidth ? `width: ${config.menuWidth}` : ''} onInteractOutside={(e) => { if (view === 'create') e.preventDefault() }}>
    {#if view === 'menu'}
      <DropdownMenu.Label>Add to canvas</DropdownMenu.Label>
      {#each widgetTypes as wt (wt.type)}
        <DropdownMenu.Item onclick={() => addWidget(wt.type)}>
          {wt.label}
        </DropdownMenu.Item>
      {/each}

      <DropdownMenu.Sub>
        <DropdownMenu.SubTrigger>Component</DropdownMenu.SubTrigger>
        <DropdownMenu.SubContent class="min-w-[200px] max-h-[320px] overflow-y-auto">
          <DropdownMenu.Item onclick={showCreateForm}>
            <span class="font-medium">Create new component…</span>
          </DropdownMenu.Item>
          {#if stories.length > 0}
            <DropdownMenu.Separator />
            <DropdownMenu.Label>Existing stories</DropdownMenu.Label>
            {#each stories as story (story.name)}
              <DropdownMenu.Item onclick={() => addStoryWidget(story.name)}>
                <span class="flex flex-col">
                  <span>{story.name}</span>
                  <span class="text-xs text-muted-foreground">{story.path}</span>
                </span>
              </DropdownMenu.Item>
            {/each}
          {/if}
        </DropdownMenu.SubContent>
      </DropdownMenu.Sub>

      <DropdownMenu.Separator />
      <div class="px-2 py-1.5 text-xs text-muted-foreground flex flex-row items-baseline"><span class="inline-flex w-2 h-2 rounded-full mr-1.5" style="background: hsl(212, 92%, 45%)"></span>Only available in dev environment</div>

    {:else if view === 'create'}
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div class="p-3 space-y-3 min-w-[280px]" onkeydown={(e) => { if (e.key === 'Enter' && canSubmit) submitCreate(); if (e.key === 'Escape') { view = 'menu' } }} onclick={(e) => e.stopPropagation()} onpointerdown={(e) => e.stopPropagation()}>
        <div class="flex items-center justify-between">
          <span class="text-sm font-medium">Create component</span>
          <button class="text-muted-foreground hover:text-foreground text-xs bg-transparent border-none cursor-pointer p-0.5" onclick={() => { view = 'menu' }}>← Back</button>
        </div>

        <div class="space-y-1">
          <Label for="sb-create-comp-name" class="text-xs">Name</Label>
          <Input id="sb-create-comp-name" placeholder="e.g. user-card" autocomplete="off" spellcheck="false" bind:value={createName} class="h-8 text-sm" />
          {#if nameError}<p class="text-xs text-destructive">{nameError}</p>{/if}
          {#if filePreview}<p class="text-xs text-muted-foreground">{filePreview}</p>{/if}
        </div>

        <fieldset class="space-y-1">
          <Label class="text-xs">Location</Label>
          <div class="flex flex-col gap-1">
            <label class="flex items-center gap-1.5 text-xs cursor-pointer">
              <input type="radio" name="sb-create-location" value="canvas" bind:group={createLocation} class="accent-primary" />
              This canvas directory
            </label>
            <label class="flex items-center gap-1.5 text-xs cursor-pointer">
              <input type="radio" name="sb-create-location" value="components" bind:group={createLocation} class="accent-primary" />
              <code class="text-xs">src/components/</code>
            </label>
          </div>
        </fieldset>

        <fieldset class="space-y-1">
          <Label class="text-xs">Format</Label>
          <div class="flex gap-3">
            <label class="flex items-center gap-1.5 text-xs cursor-pointer">
              <input type="radio" name="sb-create-format" value="jsx" bind:group={createFormat} class="accent-primary" />
              JSX
            </label>
            <label class="flex items-center gap-1.5 text-xs cursor-pointer">
              <input type="radio" name="sb-create-format" value="tsx" bind:group={createFormat} class="accent-primary" />
              TSX
            </label>
          </div>
        </fieldset>

        {#if createError}<p class="text-xs text-destructive">{createError}</p>{/if}

        <div class="flex gap-2 justify-end pt-1">
          <Button variant="outline" size="sm" onclick={() => { view = 'menu' }}>Cancel</Button>
          <Button size="sm" onclick={submitCreate} disabled={!canSubmit}>{submitting ? 'Creating…' : 'Create'}</Button>
        </div>
      </div>

    {:else if view === 'notification'}
      <div class="p-3 min-w-[260px] space-y-1">
        <p class="text-sm font-medium">✓ Component added to canvas</p>
        {#if notificationPath}
          <p class="text-xs text-muted-foreground">To edit your component, go to</p>
          <code class="text-xs block bg-muted px-2 py-1 rounded">{notificationPath}</code>
        {/if}
      </div>
    {/if}
  </DropdownMenu.Content>
</DropdownMenu.Root>

// packages/core/src/CanvasCreateMenu.jsx
/**
 * CanvasCreateMenu — CoreUIBar dropdown for adding widgets to the active canvas.
 * Dispatches custom events to bridge to React canvas system.
 * Only visible when a canvas page is active.
 */
import { useState, useMemo, useEffect, useRef } from 'react'
import { TriggerButton } from './lib/components/ui/trigger-button/index.js'
import * as DropdownMenu from './lib/components/ui/dropdown-menu/index.js'
import { Button } from './lib/components/ui/button/index.js'
import { Input } from './lib/components/ui/input/index.js'
import { Label } from './lib/components/ui/label/index.js'
import Icon from './svelte-plugin-ui/components/Icon.jsx'
import { getConfig } from './configStore.js'

const widgetTypes = [
  { type: 'sticky-note', label: 'Sticky Note' },
  { type: 'markdown', label: 'Markdown' },
  { type: 'prototype', label: 'Prototype' },
]

function getApiUrl() {
  const basePath = window.__STORYBOARD_BASE_PATH__ || '/'
  return basePath.replace(/\/$/, '') + '/_storyboard/canvas'
}

export default function CanvasCreateMenu({ config = {}, data, canvasName = '', zoom, tabindex }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [view, setView] = useState('menu')
  const [stories, setStories] = useState([])
  const [storiesLoaded, setStoriesLoaded] = useState(false)

  // Read agent configs from canvas.agents
  const agents = useMemo(() => {
    const canvasConfig = getConfig('canvas')
    const agentsConfig = canvasConfig?.agents
    if (!agentsConfig || typeof agentsConfig !== 'object') return []
    return Object.entries(agentsConfig).map(([id, cfg]) => ({
      id,
      label: cfg.label || id,
      startupCommand: cfg.startupCommand || id,
      defaultWidth: cfg.defaultWidth,
      defaultHeight: cfg.defaultHeight,
    }))
  }, [])

  // Create form state
  const [createName, setCreateName] = useState('')
  const [createLocation, setCreateLocation] = useState('canvas')
  const [createFormat, setCreateFormat] = useState('jsx')
  const [submitting, setSubmitting] = useState(false)
  const [createError, setCreateError] = useState(null)
  const [notificationPath, setNotificationPath] = useState(null)

  const kebabName = useMemo(
    () => createName.replace(/[^a-zA-Z0-9\s_-]/g, '').trim().replace(/[\s_]+/g, '-').toLowerCase().replace(/-+/g, '-').replace(/^-|-$/g, ''),
    [createName]
  )
  const nameError = useMemo(
    () => createName.trim() && !kebabName ? 'Name must contain at least one alphanumeric character' : null,
    [createName, kebabName]
  )
  const filePreview = useMemo(
    () => kebabName ? `${kebabName}.story.${createFormat}` : '',
    [kebabName, createFormat]
  )
  const canSubmit = !!kebabName && !nameError && !submitting

  function resetCreateForm() {
    setCreateName('')
    setCreateLocation('canvas')
    setCreateFormat('jsx')
    setCreateError(null)
    setSubmitting(false)
  }

  async function loadStories() {
    try {
      const res = await fetch(getApiUrl() + '/stories')
      if (res.ok) {
        const d = await res.json()
        setStories(d.stories || [])
      }
    } catch { /* ignore */ }
    setStoriesLoaded(true)
  }

  // Load stories when menu opens
  useEffect(() => {
    if (menuOpen) loadStories()
  }, [menuOpen])

  // Focus first menu item when dropdown opens on menu view
  useEffect(() => {
    if (menuOpen && view === 'menu') {
      requestAnimationFrame(() => {
        const item = document.querySelector('[data-bits-dropdown-menu-content] [data-bits-dropdown-menu-item]:not([data-disabled])')
        item?.focus()
      })
    }
  }, [menuOpen, view])

  // Reset when menu closes on menu view
  useEffect(() => {
    if (!menuOpen && view === 'menu') {
      resetCreateForm()
    }
  }, [menuOpen, view])

  function addWidget(type, props) {
    document.dispatchEvent(new CustomEvent('storyboard:canvas:add-widget', {
      detail: { type, canvasName, props }
    }))
    setMenuOpen(false)
  }

  function addStoryWidget(storyId) {
    document.dispatchEvent(new CustomEvent('storyboard:canvas:add-story-widget', {
      detail: { storyId, canvasName }
    }))
    setMenuOpen(false)
  }

  function showCreateForm() {
    resetCreateForm()
    setView('create')
  }

  const viewRef = useRef(view)
  viewRef.current = view

  async function submitCreate() {
    if (!canSubmit) return
    setSubmitting(true)
    setCreateError(null)
    try {
      const bridgeState = window.__storyboardCanvasBridgeState
      const activeCanvasId = bridgeState?.canvasId || bridgeState?.name || canvasName

      const res = await fetch(getApiUrl() + '/create-story', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: kebabName,
          location: createLocation,
          format: createFormat,
          canvasName: createLocation === 'canvas' ? activeCanvasId : undefined,
        }),
      })
      const d = await res.json()
      if (!res.ok) { setCreateError(d.error || 'Failed to create component'); setSubmitting(false); return }

      addStoryWidget(d.name)

      setNotificationPath(d.path)
      setView('notification')
      setMenuOpen(true)
      setStoriesLoaded(false)

      setTimeout(() => {
        if (viewRef.current === 'notification') {
          setMenuOpen(false)
          setView('menu')
          setNotificationPath(null)
        }
      }, 6000)
    } catch (err) {
      setCreateError(err.message || 'Network error')
    } finally {
      setSubmitting(false)
    }
  }

  function handleOpenChange(open) {
    setMenuOpen(open)
    if (!open && view !== 'menu') {
      setView('menu')
      setNotificationPath(null)
      resetCreateForm()
    }
  }

  return (
    <DropdownMenu.Root open={menuOpen} onOpenChange={handleOpenChange}>
      <DropdownMenu.Trigger asChild>
        <TriggerButton
          active={menuOpen}
          size="icon-xl"
          aria-label={config.ariaLabel || 'Add widget'}
          tabIndex={tabindex}
        >
          {config.icon ? (
            <Icon name={config.icon} size={16} {...(config.meta || {})} />
          ) : '+'}
        </TriggerButton>
      </DropdownMenu.Trigger>

      <DropdownMenu.Content
        side="top"
        align="start"
        sideOffset={16}
        className="min-w-[180px]"
        style={config.menuWidth ? { width: config.menuWidth } : undefined}
        onInteractOutside={(e) => { if (view === 'create') e.preventDefault() }}
      >
        {view === 'menu' && (
          <>
            <DropdownMenu.Label>Add to canvas</DropdownMenu.Label>
            {widgetTypes.map((wt) => (
              <DropdownMenu.Item key={wt.type} onClick={() => addWidget(wt.type)}>
                {wt.label}
              </DropdownMenu.Item>
            ))}

            {agents.length > 0 && (
              <>
                <DropdownMenu.Separator />
                <DropdownMenu.Label>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Icon name="agents" size={12} />
                    Agents
                  </span>
                </DropdownMenu.Label>
                {agents.map((agent) => (
                  <DropdownMenu.Item key={agent.id} onClick={() => addWidget('agent', {
                    agentId: agent.id,
                    startupCommand: agent.startupCommand,
                    ...(agent.defaultWidth ? { width: agent.defaultWidth } : {}),
                    ...(agent.defaultHeight ? { height: agent.defaultHeight } : {}),
                  })}>
                    {agent.label}
                  </DropdownMenu.Item>
                ))}
              </>
            )}

            <DropdownMenu.Sub>
              <DropdownMenu.SubTrigger>Component</DropdownMenu.SubTrigger>
              <DropdownMenu.SubContent className="min-w-[200px] max-h-[320px] overflow-y-auto">
                <button
                  className="relative flex cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none hover:bg-accent hover:text-accent-foreground w-full text-left bg-transparent border-none"
                  onClick={(e) => { e.preventDefault(); e.stopPropagation(); showCreateForm() }}
                  onPointerDown={(e) => e.stopPropagation()}
                >
                  <span className="font-medium">Create new component…</span>
                </button>
                {stories.length > 0 && (
                  <>
                    <DropdownMenu.Separator />
                    <DropdownMenu.Label>Existing stories</DropdownMenu.Label>
                    {stories.map((story) => (
                      <DropdownMenu.Item key={story.name} onClick={() => addStoryWidget(story.name)}>
                        <span className="flex flex-col">
                          <span>{story.name}</span>
                          <span className="text-xs text-muted-foreground">{story.path}</span>
                        </span>
                      </DropdownMenu.Item>
                    ))}
                  </>
                )}
              </DropdownMenu.SubContent>
            </DropdownMenu.Sub>

            <DropdownMenu.Separator />
            <div className="px-2 py-1.5 text-xs text-muted-foreground flex flex-row items-baseline">
              <span className="inline-flex w-2 h-2 rounded-full mr-1.5" style={{ background: 'hsl(212, 92%, 45%)' }}></span>
              Only available in dev environment
            </div>
          </>
        )}

        {view === 'create' && (
          <div
            className="p-3 space-y-3 min-w-[280px]"
            onKeyDown={(e) => { if (e.key === 'Enter' && canSubmit) submitCreate(); if (e.key === 'Escape') setView('menu') }}
            onClick={(e) => e.stopPropagation()}
            onPointerDown={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium">Create component</span>
              <button className="text-muted-foreground hover:text-foreground text-xs bg-transparent border-none cursor-pointer p-0.5" onClick={() => setView('menu')}>← Back</button>
            </div>

            <div className="space-y-1">
              <Label htmlFor="sb-create-comp-name" className="text-xs">Name</Label>
              <Input id="sb-create-comp-name" placeholder="e.g. user-card" autoComplete="off" spellCheck={false} value={createName} onChange={(e) => setCreateName(e.target.value)} className="h-8 text-sm" />
              {nameError && <p className="text-xs text-destructive">{nameError}</p>}
              {filePreview && <p className="text-xs text-muted-foreground">{filePreview}</p>}
            </div>

            <fieldset className="space-y-1">
              <Label className="text-xs">Location</Label>
              <div className="flex flex-col gap-1">
                <label className="flex items-center gap-1.5 text-xs cursor-pointer">
                  <input type="radio" name="sb-create-location" value="canvas" checked={createLocation === 'canvas'} onChange={() => setCreateLocation('canvas')} className="accent-primary" />
                  This canvas directory
                </label>
                <label className="flex items-center gap-1.5 text-xs cursor-pointer">
                  <input type="radio" name="sb-create-location" value="components" checked={createLocation === 'components'} onChange={() => setCreateLocation('components')} className="accent-primary" />
                  <code className="text-xs">src/components/</code>
                </label>
              </div>
            </fieldset>

            <fieldset className="space-y-1">
              <Label className="text-xs">Format</Label>
              <div className="flex gap-3">
                <label className="flex items-center gap-1.5 text-xs cursor-pointer">
                  <input type="radio" name="sb-create-format" value="jsx" checked={createFormat === 'jsx'} onChange={() => setCreateFormat('jsx')} className="accent-primary" />
                  JSX
                </label>
                <label className="flex items-center gap-1.5 text-xs cursor-pointer">
                  <input type="radio" name="sb-create-format" value="tsx" checked={createFormat === 'tsx'} onChange={() => setCreateFormat('tsx')} className="accent-primary" />
                  TSX
                </label>
              </div>
            </fieldset>

            {createError && <p className="text-xs text-destructive">{createError}</p>}

            <div className="flex gap-2 justify-end pt-1">
              <Button variant="outline" size="sm" onClick={() => setView('menu')}>Cancel</Button>
              <Button size="sm" onClick={submitCreate} disabled={!canSubmit}>{submitting ? 'Creating…' : 'Create'}</Button>
            </div>
          </div>
        )}

        {view === 'notification' && (
          <div className="p-3 min-w-[260px] space-y-1">
            <p className="text-sm font-medium">✓ Component added to canvas</p>
            {notificationPath && (
              <>
                <p className="text-xs text-muted-foreground">To edit your component, go to</p>
                <code className="text-xs block bg-muted px-2 py-1 rounded">{notificationPath}</code>
              </>
            )}
          </div>
        )}
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  )
}
