// packages/core/src/CommandPaletteTrigger.svelte
<!--
  CommandPaletteTrigger — toolbar button that opens the ⌘K command palette.
  Used as a tool component on the command-toolbar surface.
-->

<script lang="ts">
  import { TriggerButton } from './lib/components/ui/trigger-button/index.js'
  import Icon from './svelte-plugin-ui/components/Icon.svelte'

  interface Props {
    config?: any
    data?: any
    tabindex?: number
    localOnly?: boolean
    basePath?: string
  }

  let {
    config = {},
    tabindex,
  }: Props = $props()

  function openPalette() {
    document.dispatchEvent(new CustomEvent('storyboard:toggle-palette'))
  }
</script>

<TriggerButton
  aria-label="Command palette"
  size="icon-xl"
  {tabindex}
  onclick={openPalette}
><Icon name={config.icon || 'iconoir/select-point-3d'} size={16} {...(config.meta || {})} /></TriggerButton>

// packages/core/src/CommandPaletteTrigger.jsx
/**
 * CommandPaletteTrigger — toolbar button that opens the ⌘K command palette.
 * Used as a tool component on the command-toolbar surface.
 */

import { useCallback } from 'react'
import { TriggerButton } from './lib/components/ui/trigger-button/index.js'
import Icon from './svelte-plugin-ui/components/Icon.jsx'

export default function CommandPaletteTrigger({ config = {}, tabindex }) {
  const openPalette = useCallback(() => {
    document.dispatchEvent(new CustomEvent('storyboard:toggle-palette'))
  }, [])

  return (
    <TriggerButton
      aria-label="Command palette"
      size="icon-xl"
      tabIndex={tabindex}
      onClick={openPalette}
    >
      <Icon name={config.icon || 'iconoir/select-point-3d'} size={16} {...(config.meta || {})} />
    </TriggerButton>
  )
}
