// packages/core/src/PwaInstallBanner.svelte
<!--
  PwaInstallBanner — mobile-only "Add to Home Screen" prompt.

  Listens for the `beforeinstallprompt` event (Chrome/Edge) and shows a
  dismissible banner. Never shows on desktop or when already installed.
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { isMobile, isTouchDevice, subscribeToMobile } from './mobileViewport.js'

  const DISMISS_KEY = 'sb-pwa-install-dismissed'

  let showBanner = $state(false)
  let deferredPrompt: any = null

  function isStandalone(): boolean {
    if (typeof window === 'undefined') return false
    return (
      window.matchMedia('(display-mode: standalone)').matches ||
      (window.navigator as any).standalone === true
    )
  }

  function isDismissed(): boolean {
    try { return localStorage.getItem(DISMISS_KEY) === '1' } catch { return false }
  }

  function handleBeforeInstallPrompt(e: Event) {
    e.preventDefault()
    deferredPrompt = e
    if (isMobile() && isTouchDevice() && !isStandalone() && !isDismissed()) {
      showBanner = true
    }
  }

  async function handleInstall() {
    if (!deferredPrompt) return
    deferredPrompt.prompt()
    const { outcome } = await deferredPrompt.userChoice
    deferredPrompt = null
    showBanner = false
    if (outcome === 'dismissed') {
      try { localStorage.setItem(DISMISS_KEY, '1') } catch {}
    }
  }

  function handleDismiss() {
    showBanner = false
    try { localStorage.setItem(DISMISS_KEY, '1') } catch {}
  }

  let unsubMobile: (() => void) | null = null

  onMount(() => {
    window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
    window.addEventListener('appinstalled', () => { showBanner = false })

    unsubMobile = subscribeToMobile((mobile: boolean) => {
      if (!mobile) showBanner = false
      else if (deferredPrompt && isTouchDevice() && !isStandalone() && !isDismissed()) {
        showBanner = true
      }
    })
  })

  onDestroy(() => {
    window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
    if (unsubMobile) unsubMobile()
  })
</script>

{#if showBanner}
  <div class="pwa-banner" role="alert">
    <span class="pwa-banner-text">Add Storyboard to your home screen</span>
    <button class="pwa-banner-btn install" onclick={handleInstall}>Install</button>
    <button class="pwa-banner-btn dismiss" onclick={handleDismiss} aria-label="Dismiss">✕</button>
  </div>
{/if}

<style>
  .pwa-banner {
    position: fixed;
    bottom: 5rem;
    left: 1rem;
    right: 1rem;
    z-index: 10000;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1rem;
    background: var(--bgColor-default, #0d1117);
    color: var(--fgColor-default, #e6edf3);
    border: 1px solid var(--borderColor-default, #30363d);
    border-radius: 0.75rem;
    font-family: "Mona Sans", -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
    font-size: 0.8125rem;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);
  }

  .pwa-banner-text {
    flex: 1;
  }

  .pwa-banner-btn {
    border: none;
    border-radius: 0.375rem;
    padding: 0.375rem 0.75rem;
    font-size: 0.8125rem;
    cursor: pointer;
    font-weight: 500;
  }

  .pwa-banner-btn.install {
    background: var(--button-primary-bgColor-rest, #238636);
    color: #fff;
  }

  .pwa-banner-btn.dismiss {
    background: transparent;
    color: var(--fgColor-muted, #8d96a0);
    padding: 0.375rem;
  }
</style>

// packages/core/src/PwaInstallBanner.jsx
/**
 * PwaInstallBanner — mobile-only "Add to Home Screen" prompt.
 *
 * Listens for the `beforeinstallprompt` event (Chrome/Edge) and shows a
 * dismissible banner. Never shows on desktop or when already installed.
 */

import { useState, useEffect, useRef, useCallback } from 'react'
import { isMobile, isTouchDevice, subscribeToMobile } from './mobileViewport.js'

const DISMISS_KEY = 'sb-pwa-install-dismissed'

function isStandalone() {
  if (typeof window === 'undefined') return false
  return (
    window.matchMedia('(display-mode: standalone)').matches ||
    window.navigator.standalone === true
  )
}

function isDismissed() {
  try { return localStorage.getItem(DISMISS_KEY) === '1' } catch { return false }
}

const bannerStyle = {
  position: 'fixed',
  bottom: '5rem',
  left: '1rem',
  right: '1rem',
  zIndex: 10000,
  display: 'flex',
  alignItems: 'center',
  gap: '0.5rem',
  padding: '0.75rem 1rem',
  background: 'var(--bgColor-default, #0d1117)',
  color: 'var(--fgColor-default, #e6edf3)',
  border: '1px solid var(--borderColor-default, #30363d)',
  borderRadius: '0.75rem',
  fontFamily: '"Mona Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif',
  fontSize: '0.8125rem',
  boxShadow: '0 8px 24px rgba(0, 0, 0, 0.4)',
}

const btnBase = {
  border: 'none',
  borderRadius: '0.375rem',
  padding: '0.375rem 0.75rem',
  fontSize: '0.8125rem',
  cursor: 'pointer',
  fontWeight: 500,
}

const installBtnStyle = {
  ...btnBase,
  background: 'var(--button-primary-bgColor-rest, #238636)',
  color: '#fff',
}

const dismissBtnStyle = {
  ...btnBase,
  background: 'transparent',
  color: 'var(--fgColor-muted, #8d96a0)',
  padding: '0.375rem',
}

export default function PwaInstallBanner() {
  const [showBanner, setShowBanner] = useState(false)
  const deferredPromptRef = useRef(null)

  const handleBeforeInstallPrompt = useCallback((e) => {
    e.preventDefault()
    deferredPromptRef.current = e
    if (isMobile() && isTouchDevice() && !isStandalone() && !isDismissed()) {
      setShowBanner(true)
    }
  }, [])

  const handleInstall = useCallback(async () => {
    const prompt = deferredPromptRef.current
    if (!prompt) return
    prompt.prompt()
    const { outcome } = await prompt.userChoice
    deferredPromptRef.current = null
    setShowBanner(false)
    if (outcome === 'dismissed') {
      try { localStorage.setItem(DISMISS_KEY, '1') } catch {}
    }
  }, [])

  const handleDismiss = useCallback(() => {
    setShowBanner(false)
    try { localStorage.setItem(DISMISS_KEY, '1') } catch {}
  }, [])

  useEffect(() => {
    const handleInstalled = () => setShowBanner(false)
    window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
    window.addEventListener('appinstalled', handleInstalled)

    const unsubMobile = subscribeToMobile((mobile) => {
      if (!mobile) setShowBanner(false)
      else if (deferredPromptRef.current && isTouchDevice() && !isStandalone() && !isDismissed()) {
        setShowBanner(true)
      }
    })

    return () => {
      window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
      window.removeEventListener('appinstalled', handleInstalled)
      if (unsubMobile) unsubMobile()
    }
  }, [handleBeforeInstallPrompt])

  if (!showBanner) return null

  return (
    <div style={bannerStyle} role="alert">
      <span style={{ flex: 1 }}>Add Storyboard to your home screen</span>
      <button style={installBtnStyle} onClick={handleInstall}>Install</button>
      <button style={dismissBtnStyle} onClick={handleDismiss} aria-label="Dismiss">✕</button>
    </div>
  )
}
