// packages/core/src/ThemeMenuButton.jsx
import { useState, useEffect } from 'react'
import { TriggerButton } from './lib/components/ui/trigger-button/index.js'
import * as DropdownMenu from './lib/components/ui/dropdown-menu/index.js'
import Icon from './svelte-plugin-ui/components/Icon.jsx'
import { themeState, setTheme, getTheme, THEMES, themeSyncState, getThemeSyncTargets, setThemeSyncTarget } from './stores/themeStore.js'

export default function ThemeMenuButton({ config = {}, data, localOnly, tabindex = -1 }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [canvasActive, setCanvasActive] = useState(false)
  const [theme, setThemeState] = useState(getTheme)
  const [syncState, setSyncState] = useState(getThemeSyncTargets)

  useEffect(() => {
    const unsub = themeState.subscribe(s => setThemeState(s.theme))
    return unsub
  }, [])

  useEffect(() => {
    const unsub = themeSyncState.subscribe(s => setSyncState({ ...s }))
    return unsub
  }, [])

  useEffect(() => {
    function handleCanvasMounted() { setCanvasActive(true) }
    function handleCanvasUnmounted() { setCanvasActive(false) }
    document.addEventListener('storyboard:canvas:mounted', handleCanvasMounted)
    document.addEventListener('storyboard:canvas:unmounted', handleCanvasUnmounted)

    const state = window.__storyboardCanvasBridgeState
    const active = state?.active === true
    setCanvasActive(active)
    if (!active) {
      document.dispatchEvent(new CustomEvent('storyboard:canvas:status-request'))
    }

    return () => {
      document.removeEventListener('storyboard:canvas:mounted', handleCanvasMounted)
      document.removeEventListener('storyboard:canvas:unmounted', handleCanvasUnmounted)
    }
  }, [])

  function handleSelect(value) {
    setTheme(value)
    setMenuOpen(false)
  }

  function handleSyncToggle(e, target) {
    e.preventDefault()
    setThemeSyncTarget(target, !syncState[target])
  }

  return (
    <DropdownMenu.Root open={menuOpen} onOpenChange={setMenuOpen}>
      <DropdownMenu.Trigger>
          <TriggerButton
            active={menuOpen}
            size="icon-xl"
            aria-label={config.ariaLabel || 'Theme'}
            tabIndex={tabindex}
          >
            <Icon name={config.icon || 'primer/sun'} size={16} {...(config.meta || {})} />
          </TriggerButton>
      </DropdownMenu.Trigger>

      <DropdownMenu.Content
        side="top"
        align="end"
        sideOffset={16}
        style={config.menuWidth ? { minWidth: config.menuWidth } : undefined}
        className="min-w-[200px]"
      >
        {config.label && <DropdownMenu.Label>{config.label}</DropdownMenu.Label>}

        <DropdownMenu.RadioGroup value={theme}>
          {THEMES.map((option) => (
            <DropdownMenu.RadioItem
              key={option.value}
              value={option.value}
              onClick={() => handleSelect(option.value)}
            >
              {option.name}
            </DropdownMenu.RadioItem>
          ))}
        </DropdownMenu.RadioGroup>

        <DropdownMenu.Separator />

        <DropdownMenu.Sub>
          <DropdownMenu.SubTrigger>Theme settings</DropdownMenu.SubTrigger>
          <DropdownMenu.SubContent className="min-w-[180px]">
            <DropdownMenu.Label>Apply theme to</DropdownMenu.Label>
            {canvasActive ? (
              <DropdownMenu.CheckboxItem
                checked={syncState.canvas}
                onSelect={(e) => handleSyncToggle(e, 'canvas')}
              >
                Canvas
              </DropdownMenu.CheckboxItem>
            ) : (
              <DropdownMenu.CheckboxItem
                checked={syncState.prototype}
                onSelect={(e) => handleSyncToggle(e, 'prototype')}
              >
                Prototype
              </DropdownMenu.CheckboxItem>
            )}
            <DropdownMenu.CheckboxItem
              checked={syncState.toolbar}
              onSelect={(e) => handleSyncToggle(e, 'toolbar')}
            >
              Tools
            </DropdownMenu.CheckboxItem>
            <DropdownMenu.CheckboxItem
              checked={syncState.codeBoxes}
              onSelect={(e) => handleSyncToggle(e, 'codeBoxes')}
            >
              Code boxes
            </DropdownMenu.CheckboxItem>
          </DropdownMenu.SubContent>
        </DropdownMenu.Sub>
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  )
}

// packages/core/src/ThemeMenuButton.svelte
<!--
  ThemeMenuButton — toolbar dropdown for switching the app color scheme.

  Renders a radio group of theme options (System, Light, Dark, etc.),
  followed by a separator and "Theme settings" submenu with sync toggles.
-->

<script lang="ts">
  import { TriggerButton } from './lib/components/ui/trigger-button/index.js'
  import * as DropdownMenu from './lib/components/ui/dropdown-menu/index.js'
  import Icon from './svelte-plugin-ui/components/Icon.svelte'
  import { themeState, setTheme, THEMES, type ThemeValue, themeSyncState, setThemeSyncTarget, type ThemeSyncTargets } from './stores/themeStore.js'

  interface Props {
    config?: {
      ariaLabel?: string
      icon?: string
      meta?: Record<string, any>
      label?: string
      menuWidth?: string
    }
    data?: any
    localOnly?: boolean
    tabindex?: number
  }

  let { config = {}, data, localOnly, tabindex = -1 }: Props = $props()

  let menuOpen = $state(false)
  let canvasActive = $state(false)

  function handleSelect(value: ThemeValue) {
    setTheme(value)
    menuOpen = false
  }

  function handleSyncToggle(e: Event, target: keyof ThemeSyncTargets) {
    e.preventDefault()
    setThemeSyncTarget(target, !$themeSyncState[target])
  }

  $effect(() => {
    function handleCanvasMounted() {
      canvasActive = true
    }
    function handleCanvasUnmounted() {
      canvasActive = false
    }
    document.addEventListener('storyboard:canvas:mounted', handleCanvasMounted)
    document.addEventListener('storyboard:canvas:unmounted', handleCanvasUnmounted)

    const state = (window as any).__storyboardCanvasBridgeState
    canvasActive = state?.active === true
    if (!canvasActive) {
      document.dispatchEvent(new CustomEvent('storyboard:canvas:status-request'))
    }

    return () => {
      document.removeEventListener('storyboard:canvas:mounted', handleCanvasMounted)
      document.removeEventListener('storyboard:canvas:unmounted', handleCanvasUnmounted)
    }
  })
</script>

<DropdownMenu.Root bind:open={menuOpen}>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <TriggerButton
        active={menuOpen}
        size="icon-xl"
        aria-label={config.ariaLabel || 'Theme'}
        {tabindex}
        {...props}
      >
        <Icon name={config.icon || 'primer/sun'} size={16} {...(config.meta || {})} />
      </TriggerButton>
    {/snippet}
  </DropdownMenu.Trigger>

  <DropdownMenu.Content side="top" align="end" sideOffset={16} style={config.menuWidth ? `min-width: ${config.menuWidth}` : undefined} class="min-w-[200px]">
    {#if config.label}
      <DropdownMenu.Label>{config.label}</DropdownMenu.Label>
    {/if}

    <DropdownMenu.RadioGroup value={$themeState.theme}>
      {#each THEMES as option (option.value)}
        <DropdownMenu.RadioItem
          value={option.value}
          onclick={() => handleSelect(option.value)}
        >
          {option.name}
        </DropdownMenu.RadioItem>
      {/each}
    </DropdownMenu.RadioGroup>

    <DropdownMenu.Separator />

    <DropdownMenu.Sub>
      <DropdownMenu.SubTrigger>Theme settings</DropdownMenu.SubTrigger>
      <DropdownMenu.SubContent class="min-w-[180px]">
        <DropdownMenu.Label>Apply theme to</DropdownMenu.Label>
        {#if canvasActive}
          <DropdownMenu.CheckboxItem
            checked={$themeSyncState.canvas}
            onSelect={(e) => handleSyncToggle(e, 'canvas')}
          >
            Canvas
          </DropdownMenu.CheckboxItem>
        {:else}
          <DropdownMenu.CheckboxItem
            checked={$themeSyncState.prototype}
            onSelect={(e) => handleSyncToggle(e, 'prototype')}
          >
            Prototype
          </DropdownMenu.CheckboxItem>
        {/if}
        <DropdownMenu.CheckboxItem
          checked={$themeSyncState.toolbar}
          onSelect={(e) => handleSyncToggle(e, 'toolbar')}
        >
          Tools
        </DropdownMenu.CheckboxItem>
        <DropdownMenu.CheckboxItem
          checked={$themeSyncState.codeBoxes}
          onSelect={(e) => handleSyncToggle(e, 'codeBoxes')}
        >
          Code boxes
        </DropdownMenu.CheckboxItem>
      </DropdownMenu.SubContent>
    </DropdownMenu.Sub>
  </DropdownMenu.Content>
</DropdownMenu.Root>
