// packages/core/src/workshop/features/createStory/CreateStoryForm.svelte
<!--
  CreateStoryForm — workshop form for creating a new .story.jsx/.tsx file.
  Scaffolds a story file via the canvas server API.
-->

<script lang="ts">
  import { onMount } from 'svelte'
  import { Button } from '../../../lib/components/ui/button/index.js'
  import { Input } from '../../../lib/components/ui/input/index.js'
  import { Label } from '../../../lib/components/ui/label/index.js'
  import * as Panel from '../../../lib/components/ui/panel/index.js'
  import * as Alert from '../../../lib/components/ui/alert/index.js'

  interface Props { onClose?: () => void }
  let { onClose }: Props = $props()

  let name = $state('')
  let location = $state('canvas')
  let format = $state('jsx')

  let submitting = $state(false)
  let error: string | null = $state(null)
  let success: string | null = $state(null)
  let createdPath: string | null = $state(null)

  // Pre-fill canvasId from the active canvas (set by CanvasPage bridge)
  let canvasId = $state('')

  const kebabName = $derived(
    name.replace(/[^a-zA-Z0-9\s_-]/g, '').trim().replace(/[\s_]+/g, '-').toLowerCase().replace(/-+/g, '-').replace(/^-|-$/g, '')
  )

  const nameError = $derived(
    name.trim() && !kebabName ? 'Name must contain at least one alphanumeric character'
    : name.trim() && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(kebabName) ? 'Name must be kebab-case'
    : null
  )

  const filePreview = $derived(
    kebabName ? `${kebabName}.story.${format}` : ''
  )

  const canSubmit = $derived(!!kebabName && !nameError && !submitting)

  const STORY_SUCCESS_KEY = 'sb-story-created'

  function getApiUrl() {
    const basePath = (window as any).__STORYBOARD_BASE_PATH__ || '/'
    return basePath.replace(/\/$/, '') + '/_storyboard/canvas'
  }

  onMount(() => {
    // Read active canvas ID from the bridge state (window, not sessionStorage)
    try {
      const bridgeState = (window as any).__storyboardCanvasBridgeState
      if (bridgeState?.canvasId) canvasId = bridgeState.canvasId
      else if (bridgeState?.name) canvasId = bridgeState.name
    } catch {}

    // Restore success state after Vite full-reload
    try {
      const saved = sessionStorage.getItem(STORY_SUCCESS_KEY)
      if (saved) {
        const parsed = JSON.parse(saved)
        success = parsed.success
        createdPath = parsed.path
        sessionStorage.removeItem(STORY_SUCCESS_KEY)
      }
    } catch {}
  })

  async function submit() {
    if (!canSubmit) return
    submitting = true; error = null; success = null; createdPath = null
    try {
      const res = await fetch(getApiUrl() + '/create-story', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: kebabName,
          location,
          format,
          canvasName: location === 'canvas' ? canvasId : undefined,
        }),
      })
      const data = await res.json()
      if (!res.ok) { error = data.error || 'Failed to create story'; return }
      success = `Created ${data.path}`
      createdPath = data.path
      // Persist for toast after Vite reload
      try {
        sessionStorage.setItem(STORY_SUCCESS_KEY, JSON.stringify({
          success: `Created ${data.name}.story.${format}`,
          path: data.path,
        }))
      } catch {}
    } catch (err: any) { error = err.message || 'Network error' } finally { submitting = false }
  }

  function handleKeydown(e: KeyboardEvent) { if (e.key === 'Enter' && canSubmit) submit() }
</script>

<Panel.Header>
  <Panel.Title>Create story</Panel.Title>
  <Panel.Close />
</Panel.Header>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="p-4 pt-2 space-y-3" onkeydown={handleKeydown}>
  <div class="space-y-1">
    <Label for="sb-story-name">Component name</Label>
    <Input id="sb-story-name" placeholder="e.g. user-card" autocomplete="off" spellcheck="false" bind:value={name} />
    {#if nameError}<p class="text-sm text-destructive">{nameError}</p>{/if}
    {#if filePreview}<p class="text-xs text-muted-foreground">File: <code class="px-1 py-0.5 bg-muted rounded font-mono text-foreground text-xs">{filePreview}</code></p>{/if}
  </div>

  <fieldset class="space-y-1.5">
    <Label>Location</Label>
    <div class="flex flex-col gap-1.5">
      <label class="flex items-center gap-2 text-sm cursor-pointer">
        <input type="radio" name="sb-story-location" value="canvas" bind:group={location} class="accent-primary" />
        This canvas directory
      </label>
      <label class="flex items-center gap-2 text-sm cursor-pointer">
        <input type="radio" name="sb-story-location" value="components" bind:group={location} class="accent-primary" />
        <code class="text-xs bg-muted px-1 py-0.5 rounded">src/components/</code>
      </label>
    </div>
  </fieldset>

  <fieldset class="space-y-1.5">
    <Label>Format</Label>
    <div class="flex gap-3">
      <label class="flex items-center gap-2 text-sm cursor-pointer">
        <input type="radio" name="sb-story-format" value="jsx" bind:group={format} class="accent-primary" />
        JSX
      </label>
      <label class="flex items-center gap-2 text-sm cursor-pointer">
        <input type="radio" name="sb-story-format" value="tsx" bind:group={format} class="accent-primary" />
        TSX
      </label>
    </div>
  </fieldset>

  {#if error}<Alert.Root variant="destructive"><Alert.Description>{error}</Alert.Description></Alert.Root>{/if}
  {#if success}
    <Alert.Root>
      <Alert.Description class="text-success">
        {success}
        {#if createdPath}
          <br /><span class="text-xs text-muted-foreground">To edit your component, go to <code class="px-1 py-0.5 bg-muted rounded font-mono text-xs">{createdPath}</code></span>
        {/if}
      </Alert.Description>
    </Alert.Root>
  {/if}
</div>

<Panel.Footer>
  <Button variant="outline" onclick={onClose}>Cancel</Button>
  <Button onclick={submit} disabled={!canSubmit}>{submitting ? 'Creating\u2026' : 'Create'}</Button>
</Panel.Footer>

// packages/core/src/workshop/features/createStory/CreateStoryForm.jsx
import { useState, useMemo, useEffect } from 'react'
import { Button } from '../../../lib/components/ui/button/index.js'
import { Input } from '../../../lib/components/ui/input/index.js'
import { Label } from '../../../lib/components/ui/label/index.js'
import * as Panel from '../../../lib/components/ui/panel/index.js'
import * as Alert from '../../../lib/components/ui/alert/index.js'

const STORY_SUCCESS_KEY = 'sb-story-created'

function getApiUrl() {
  const basePath = window.__STORYBOARD_BASE_PATH__ || '/'
  return basePath.replace(/\/$/, '') + '/_storyboard/canvas'
}

export default function CreateStoryForm({ onClose }) {
  const [name, setName] = useState('')
  const [location, setLocation] = useState('canvas')
  const [format, setFormat] = useState('jsx')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState(null)
  const [success, setSuccess] = useState(null)
  const [createdPath, setCreatedPath] = useState(null)
  const [canvasId, setCanvasId] = useState('')

  const kebabName = useMemo(
    () => name.replace(/[^a-zA-Z0-9\s_-]/g, '').trim().replace(/[\s_]+/g, '-').toLowerCase().replace(/-+/g, '-').replace(/^-|-$/g, ''),
    [name]
  )

  const nameError = useMemo(() => {
    if (name.trim() && !kebabName) return 'Name must contain at least one alphanumeric character'
    if (name.trim() && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(kebabName)) return 'Name must be kebab-case'
    return null
  }, [name, kebabName])

  const filePreview = kebabName ? `${kebabName}.story.${format}` : ''
  const canSubmit = !!kebabName && !nameError && !submitting

  useEffect(() => {
    try {
      const bridgeState = window.__storyboardCanvasBridgeState
      if (bridgeState?.canvasId) setCanvasId(bridgeState.canvasId)
      else if (bridgeState?.name) setCanvasId(bridgeState.name)
    } catch {}

    try {
      const saved = sessionStorage.getItem(STORY_SUCCESS_KEY)
      if (saved) {
        const parsed = JSON.parse(saved)
        setSuccess(parsed.success)
        setCreatedPath(parsed.path)
        sessionStorage.removeItem(STORY_SUCCESS_KEY)
      }
    } catch {}
  }, [])

  async function submit() {
    if (!canSubmit) return
    setSubmitting(true)
    setError(null)
    setSuccess(null)
    setCreatedPath(null)
    try {
      const res = await fetch(getApiUrl() + '/create-story', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: kebabName,
          location,
          format,
          canvasName: location === 'canvas' ? canvasId : undefined,
        }),
      })
      const data = await res.json()
      if (!res.ok) { setError(data.error || 'Failed to create story'); return }
      setSuccess(`Created ${data.path}`)
      setCreatedPath(data.path)
      try {
        sessionStorage.setItem(STORY_SUCCESS_KEY, JSON.stringify({
          success: `Created ${data.name}.story.${format}`,
          path: data.path,
        }))
      } catch {}
    } catch (err) {
      setError(err.message || 'Network error')
    } finally {
      setSubmitting(false)
    }
  }

  function handleKeydown(e) {
    if (e.key === 'Enter' && canSubmit) submit()
  }

  return (
    <>
      <Panel.Header>
        <Panel.Title>Create story</Panel.Title>
        <Panel.Close />
      </Panel.Header>

      <div className="p-4 pt-2 space-y-3" onKeyDown={handleKeydown}>
        <div className="space-y-1">
          <Label htmlFor="sb-story-name">Component name</Label>
          <Input
            id="sb-story-name"
            placeholder="e.g. user-card"
            autoComplete="off"
            spellCheck={false}
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          {nameError && <p className="text-sm text-destructive">{nameError}</p>}
          {filePreview && (
            <p className="text-xs text-muted-foreground">
              File: <code className="px-1 py-0.5 bg-muted rounded font-mono text-foreground text-xs">{filePreview}</code>
            </p>
          )}
        </div>

        <fieldset className="space-y-1.5">
          <Label>Location</Label>
          <div className="flex flex-col gap-1.5">
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <input
                type="radio"
                name="sb-story-location"
                value="canvas"
                checked={location === 'canvas'}
                onChange={() => setLocation('canvas')}
                className="accent-primary"
              />
              This canvas directory
            </label>
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <input
                type="radio"
                name="sb-story-location"
                value="components"
                checked={location === 'components'}
                onChange={() => setLocation('components')}
                className="accent-primary"
              />
              <code className="text-xs bg-muted px-1 py-0.5 rounded">src/components/</code>
            </label>
          </div>
        </fieldset>

        <fieldset className="space-y-1.5">
          <Label>Format</Label>
          <div className="flex gap-3">
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <input
                type="radio"
                name="sb-story-format"
                value="jsx"
                checked={format === 'jsx'}
                onChange={() => setFormat('jsx')}
                className="accent-primary"
              />
              JSX
            </label>
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <input
                type="radio"
                name="sb-story-format"
                value="tsx"
                checked={format === 'tsx'}
                onChange={() => setFormat('tsx')}
                className="accent-primary"
              />
              TSX
            </label>
          </div>
        </fieldset>

        {error && (
          <Alert.Root variant="destructive">
            <Alert.Description>{error}</Alert.Description>
          </Alert.Root>
        )}
        {success && (
          <Alert.Root>
            <Alert.Description className="text-success">
              {success}
              {createdPath && (
                <>
                  <br />
                  <span className="text-xs text-muted-foreground">
                    To edit your component, go to{' '}
                    <code className="px-1 py-0.5 bg-muted rounded font-mono text-xs">{createdPath}</code>
                  </span>
                </>
              )}
            </Alert.Description>
          </Alert.Root>
        )}
      </div>

      <Panel.Footer>
        <Button variant="outline" onClick={onClose}>Cancel</Button>
        <Button onClick={submit} disabled={!canSubmit}>
          {submitting ? 'Creating\u2026' : 'Create'}
        </Button>
      </Panel.Footer>
    </>
  )
}
