// packages/core/src/svelte-plugin-ui/components/Viewfinder.svelte
<!--
  Viewfinder — prototype index and flow dashboard.

  Full-page component that lists prototypes as expandable groups,
  each showing its flows. Global flows (not belonging to any prototype)
  appear as an "Other flows" group.

  Mounted via mountViewfinder() from the viewfinder plugin entry point.
-->

<script lang="ts">
  import { buildPrototypeIndex } from '../../viewfinder.js'
  import Octicon from './Octicon.svelte'

  interface Props {
    title?: string
    subtitle?: string
    basePath?: string
    knownRoutes?: string[]
    showThumbnails?: boolean
    hideDefaultFlow?: boolean
  }

  let {
    title = 'Storyboard',
    subtitle = '',
    basePath = '/',
    knownRoutes = [],
    showThumbnails = false,
    hideDefaultFlow = false,
  }: Props = $props()

  const prototypeIndex = $derived(buildPrototypeIndex(knownRoutes))

  const globalFlows = $derived(
    hideDefaultFlow
      ? prototypeIndex.globalFlows.filter((f: any) => f.key !== 'default')
      : prototypeIndex.globalFlows
  )

  // Build a flat display list: folders (with nested prototypes), ungrouped prototypes, global flows
  const ungroupedProtos = $derived(prototypeIndex.prototypes)

  const folders = $derived(prototypeIndex.folders || [])

  const otherFlows = $derived.by(() => {
    if (globalFlows.length === 0) return null
    return {
      name: 'Other flows',
      dirName: '__global__',
      description: null,
      author: null,
      gitAuthor: null,
      lastModified: null,
      icon: null,
      team: null,
      tags: null,
      flows: globalFlows,
    }
  })

  const totalProtos = $derived(
    ungroupedProtos.length + folders.reduce((sum: number, f: any) => sum + f.prototypes.length, 0)
  )

  const totalFlows = $derived(
    ungroupedProtos.reduce((sum: number, p: any) => sum + p.flows.length, 0) +
    globalFlows.length +
    folders.reduce((sum: number, f: any) =>
      sum + f.prototypes.reduce((s: number, p: any) => s + p.flows.length, 0), 0)
  )

  // Sorting — use pre-sorted arrays from buildPrototypeIndex
  type SortMode = 'updated' | 'title'
  let sortBy: SortMode = $state('updated')

  const sortedProtos = $derived(prototypeIndex.sorted?.[sortBy]?.prototypes ?? ungroupedProtos)
  const sortedFolders = $derived(prototypeIndex.sorted?.[sortBy]?.folders ?? folders)

  // Expanded state — all prototypes and folders start expanded
  let expanded: Record<string, boolean> = $state({})

  function isExpanded(dirName: string): boolean {
    return expanded[dirName] ?? true
  }

  function toggle(dirName: string) {
    expanded[dirName] = !isExpanded(dirName)
  }

  function protoRoute(dirName: string): string {
    return `/${dirName}`
  }

  function formatName(name: string): string {
    return name
      .split('-')
      .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ')
  }

  function placeholderSvg(name: string): string {
    const h = (function hashStr(s: string) {
      let v = 0
      for (let i = 0; i < s.length; i++) v = ((v << 5) - v + s.charCodeAt(i)) | 0
      return Math.abs(v)
    })(name)

    let rects = ''
    for (let i = 0; i < 12; i++) {
      const s = h * (i + 1)
      const x = (s * 7 + i * 31) % 320
      const y = (s * 13 + i * 17) % 200
      const w = 20 + (s * (i + 3)) % 80
      const ht = 8 + (s * (i + 7)) % 40
      const opacity = 0.06 + ((s * (i + 2)) % 20) / 100
      const fill = i % 3 === 0 ? 'var(--placeholder-accent)' : i % 3 === 1 ? 'var(--placeholder-fg)' : 'var(--placeholder-muted)'
      rects += `<rect x="${x}" y="${y}" width="${w}" height="${ht}" rx="2" fill="${fill}" opacity="${opacity}" />`
    }

    let lines = ''
    for (let i = 0; i < 6; i++) {
      const s = h * (i + 5)
      const y = 10 + (s % 180)
      lines += `<line x1="0" y1="${y}" x2="320" y2="${y}" stroke="var(--placeholder-grid)" stroke-width="0.5" opacity="0.4" />`
    }
    for (let i = 0; i < 8; i++) {
      const s = h * (i + 9)
      const x = 10 + (s % 300)
      lines += `<line x1="${x}" y1="0" x2="${x}" y2="200" stroke="var(--placeholder-grid)" stroke-width="0.5" opacity="0.3" />`
    }

    return `<svg viewBox="0 0 320 200" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><rect width="320" height="200" fill="var(--placeholder-bg)" />${lines}${rects}</svg>`
  }

  // Branch switching
  interface Branch { branch: string; folder: string }

  const MOCK_BRANCHES: Branch[] = [
    { branch: 'main', folder: '' },
    { branch: 'feat/comments-v2', folder: 'branch--feat-comments-v2' },
    { branch: 'fix/nav-overflow', folder: 'branch--fix-nav-overflow' },
  ]

  let branches: Branch[] | null = $state(null)

  const branchBasePath = $derived(
    (basePath || '/storyboard-source/').replace(/\/branch--[^/]*\/$/, '/')
  )

  const currentBranch = $derived(
    (() => {
      const m = (basePath || '').match(/\/branch--([^/]+)\/?$/)
      return m ? m[1] : 'main'
    })()
  )

  $effect(() => {
    fetch(`${branchBasePath}branches.json`)
      .then(r => r.ok ? r.json() : null)
      .then((data: any) => {
        branches = Array.isArray(data) && data.length > 0 ? data : MOCK_BRANCHES
      })
      .catch(() => { branches = MOCK_BRANCHES })
  })

  function handleBranchChange(e: Event) {
    const folder = (e.target as HTMLSelectElement).value
    if (folder) {
      window.location.href = `${branchBasePath}${folder}/`
    }
  }
</script>

<div class="container">
  <header class="header">
    <div class="headerTop">
      <div>
        <h1 class="title">{title}</h1>
        {#if subtitle}
          <p class="subtitle">{subtitle}</p>
        {/if}
      </div>
    </div>
    <div class="controlsRow">
      <!-- <span class="sceneCount">
        {(folders.length > 0 ? `${folders.length} folder${folders.length !== 1 ? 's' : ''} · ` : '') + `${totalProtos} prototype${totalProtos !== 1 ? 's' : ''} · ${totalFlows} flow${totalFlows !== 1 ? 's' : ''}`}
      </span> -->
      <div class="sortToggle">
        <button
          class="sortButton"
          class:sortButtonActive={sortBy === 'updated'}
          onclick={() => sortBy = 'updated'}
        >
          <Octicon name="clock" size={14} offsetY={-1} />
          Last updated
        </button>
        <button
          class="sortButton"
          class:sortButtonActive={sortBy === 'title'}
          onclick={() => sortBy = 'title'}
        >
          <Octicon name="sort-asc" size={14} offsetY={-1} />
          Title A–Z
        </button>
      </div>
      {#if branches && branches.length > 0}
        <div class="branchDropdown">
          <span class="branchIcon"><Octicon size={16} color="var(--fgColor-muted)" offsetY={-1} offsetX={2} name="git-branch" /></span>
          <select
            class="branchSelect"
            onchange={handleBranchChange}
            aria-label="Switch branch"
          >
            <option value="" disabled selected>{currentBranch}</option>
            {#each branches as b (b.folder)}
              <option value={b.folder}>{b.branch}</option>
            {/each}
          </select>
        </div>
      {/if}
    </div>
  </header>

  {#if totalProtos === 0 && folders.length === 0}
    <p class="empty">No flows found. Add a <code>*.flow.json</code> file to get started.</p>
  {:else}
    <div class="list">
      {#snippet protoEntry(proto)}
        <section class="protoGroup">
          {#if proto.hideFlows && proto.flows.length === 1}
            <!-- Single flow, hidden — navigates directly to the flow -->
            <a class="listItem" href={proto.flows[0].route}>
              <div class="cardBody">
                <p class="protoName" class:otherflows={proto.dirName === '__global__'}>
                  {#if proto.icon}<span class="protoIcon">{proto.icon}</span>{/if}
                  {proto.name}
                </p>
                {#if proto.description}
                  <p class="protoDesc">{proto.description}</p>
                {/if}
                {#if proto.author}
                  {@const authors = Array.isArray(proto.author) ? proto.author : [proto.author]}
                  <div class="author">
                    <span class="authorAvatars">
                      {#each authors as a (a)}
                        <img
                          src="https://github.com/{a}.png?size=48"
                          alt={a}
                          class="authorAvatar"
                        />
                      {/each}
                    </span>
                    <span class="authorName">{authors.join(', ')}</span>
                  </div>
                {:else if proto.gitAuthor}
                  <p class="authorPlain">{proto.gitAuthor}</p>
                {/if}
              </div>
            </a>
          {:else if proto.flows.length > 0}
            <!-- Expandable prototype with flows -->
            <button
              class="listItem protoHeader"
              onclick={() => toggle(proto.dirName)}
              aria-expanded={isExpanded(proto.dirName)}
            >
              <div class="cardBody">
                <p class="protoName" class:otherflows={proto.dirName === '__global__'}>
                  {#if proto.icon}<span class="protoIcon">{proto.icon}</span>{/if}
                  {proto.name}
                  <span class="protoChevron">
                    {#if isExpanded(proto.dirName)}
                      <Octicon size={12} color="var(--fgColor-disabled)" name="chevron-down" offsetY={-3} offsetX={2} />
                    {:else}
                      <Octicon size={12} color="var(--fgColor-disabled)" name="chevron-right" offsetY={-3} offsetX={2} />
                    {/if}
                  </span>
                </p>
                {#if proto.description}
                  <p class="protoDesc">{proto.description}</p>
                {/if}
                {#if proto.author}
                  {@const authors = Array.isArray(proto.author) ? proto.author : [proto.author]}
                  <div class="author">
                    <span class="authorAvatars">
                      {#each authors as a (a)}
                        <img
                          src="https://github.com/{a}.png?size=48"
                          alt={a}
                          class="authorAvatar"
                        />
                      {/each}
                    </span>
                    <span class="authorName">{authors.join(', ')}</span>
                  </div>
                {:else if proto.gitAuthor}
                  <p class="authorPlain">{proto.gitAuthor}</p>
                {/if}
              </div>
            </button>
          {:else}
            <!-- Prototype with no flows — navigates directly -->
            <a class="listItem" href={protoRoute(proto.dirName)}>
              <div class="cardBody">
                <p class="protoName" class:otherflows={proto.dirName === '__global__'}>
                  {#if proto.icon}<span class="protoIcon">{proto.icon}</span>{/if}
                  {proto.name}
                </p>
                {#if proto.description}
                  <p class="protoDesc">{proto.description}</p>
                {/if}
                {#if proto.author}
                  {@const authors = Array.isArray(proto.author) ? proto.author : [proto.author]}
                  <div class="author">
                    <span class="authorAvatars">
                      {#each authors as a (a)}
                        <img
                          src="https://github.com/{a}.png?size=48"
                          alt={a}
                          class="authorAvatar"
                        />
                      {/each}
                    </span>
                    <span class="authorName">{authors.join(', ')}</span>
                  </div>
                {:else if proto.gitAuthor}
                  <p class="authorPlain">{proto.gitAuthor}</p>
                {/if}
              </div>
            </a>
          {/if}

          {#if !(proto.hideFlows && proto.flows.length === 1) && isExpanded(proto.dirName) && proto.flows.length > 0}
            <div class="flowList">
              {#each proto.flows as flow (flow.key)}
                <a href={flow.route} class="listItem flowItem">
                  {#if showThumbnails}
                    <div class="thumbnail">
                      {@html placeholderSvg(flow.key)}
                    </div>
                  {/if}
                  <div class="cardBody">
                    <p class="protoName">{flow.meta?.title || formatName(flow.name)}</p>
                    {#if flow.meta?.description}
                      <p class="flowDesc">{flow.meta.description}</p>
                    {/if}
                  </div>
                </a>
              {/each}
            </div>
          {/if}
        </section>
      {/snippet}

      <!-- Folders with their prototypes -->
      {#each sortedFolders as folder (folder.dirName)}
        <section class="folderGroup" class:folderGroupOpen={isExpanded(`folder:${folder.dirName}`)}>
          <button
            class="folderHeader"
            onclick={() => toggle(`folder:${folder.dirName}`)}
            aria-expanded={isExpanded(`folder:${folder.dirName}`)}
          >
            <p class="folderName">
              <span>
                {#if isExpanded(`folder:${folder.dirName}`)}
                  <Octicon size={20} offsetY={-1.5} name="folder-open" color="#54aeff" />
                {:else}
                  <Octicon size={20} offsetY={-1.5} name="folder" color="#54aeff" />
                {/if}
              </span>
              {folder.name}
            </p>
            {#if folder.description}
              <p class="folderDesc">{folder.description}</p>
            {/if}
          </button>
          {#if isExpanded(`folder:${folder.dirName}`) && folder.prototypes.length > 0}
            <div class="folderContent">
              {#each folder.prototypes as proto (proto.dirName)}
                {@render protoEntry(proto)}
              {/each}
            </div>
          {/if}
        </section>
      {/each}

      <!-- Ungrouped prototypes (not in any folder) -->
      {#each sortedProtos as proto (proto.dirName)}
        {@render protoEntry(proto)}
      {/each}

      <!-- Other flows (always at the bottom) -->
      {#if otherFlows}
        {@render protoEntry(otherFlows)}
      {/if}
    </div>
  {/if}
</div>

<style>
  .container {
    min-height: 100vh;
    background-color: var(--bgColor-default, #0d1117);
    color: var(--fgColor-default, #e6edf3);
    padding: 80px 32px 48px;
  }

  .header {
    max-width: 720px;
    margin: 0 auto 64px;
  }

  .headerTop {
    display: flex;
    align-items: baseline;
    gap: 16px;
  }

  .title {
    font: var(--text-display-shorthand); 
    margin: 0 0 12px;
    color: var(--fgColor-default, #e6edf3);
    letter-spacing: -0.03em;
    line-height: 1;
  }

  .subtitle {
    font-size: 15px;
    color: var(--fgColor-muted, #848d97);
    margin: 4px 0 0;
    letter-spacing: 0.01em;
  }

  .controlsRow {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 16px 0 0;
  }

  /* .sceneCount {
    font-size: 13px;
    color: var(--fgColor-muted, #848d97);
    letter-spacing: 0.01em;
    white-space: nowrap;
  } */

  .sortToggle {
    display: flex;
    gap: 4px;
  }

  .sortButton {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 4px 10px;
    font-size: 12px;
    font-family: inherit;
    color: var(--fgColor-muted, #848d97);
    background: transparent;
    border: 1px solid transparent;
    border-radius: 6px;
    cursor: pointer;
    transition: color 0.15s, background 0.15s, border-color 0.15s;
  }

  .sortButton:hover {
    color: var(--fgColor-default, #e6edf3);
    background: var(--bgColor-neutral-muted, rgba(110, 118, 129, 0.1));
  }

  .sortButtonActive {
    color: var(--fgColor-default, #e6edf3);
    background: var(--bgColor-neutral-muted, rgba(110, 118, 129, 0.15));
    border-color: var(--borderColor-muted, #30363d);
  }

  .branchDropdown {
    display: flex;
    align-items: center;
    gap: 0;
    flex-shrink: 0;
    position: relative;
    margin-left: auto;
  }

  .branchIcon {
    position: absolute;
    left: 10px;
    color: var(--fgColor-muted, #848d97);
    pointer-events: none;
    z-index: 1;
  }

  .branchSelect {
    appearance: none;
    background-color: transparent;
    color: var(--fgColor-default, #e6edf3);
    border: 1px solid var(--borderColor-default, #30363d);
    border-radius: 20px;
    padding: 6px 32px 6px 32px;
    font-size: 13px;
    font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
    cursor: pointer;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' fill='%23848d97'%3E%3Cpath d='M6 8.5L1.5 4h9L6 8.5z'/%3E%3C/svg%3E");
    background-repeat: no-repeat;
    background-position: right 12px center;
    min-width: 140px;
    max-width: 220px;
    text-overflow: ellipsis;
    overflow: hidden;
    transition: border-color 0.15s ease;
  }

  .branchSelect:hover {
    border-color: var(--fgColor-muted, #848d97);
  }

  .branchSelect:focus-visible {
    outline: 2px solid var(--borderColor-accent-emphasis, #1f6feb);
    outline-offset: -1px;
  }

  .list {
    display: flex;
    flex-direction: column;
    max-width: 720px;
    margin: 0 auto;
  }

  .protoGroup {
    display: flex;
    flex-direction: column;
  }

  .folderGroup {
    display: flex;
    flex-direction: column;
  }

  .folderGroup:not(:first-child) {
    margin-top: 24px;
  }

  .folderHeader {
    display: flex;
    flex-direction: row;
    align-items: baseline;
    justify-content: flex-start;
    gap: var(--base-size-8);
    appearance: none;
    border: none;
    border-radius: var(--base-size-6);
    background: none;
    width: 100%;
    text-align: left;
    cursor: pointer;
    color: inherit;
    padding: var(--base-size-16);

    &:hover,
    .folderGroupOpen & {
      background-color: var(--bgColor-muted, #161b22);
    }
  }


  .folderGroupOpen .folderHeader {
    background-color: var(--bgColor-muted, #161b22);
  }


  .folderName {
    display: inline-flex;
    align-items: center;
    gap: var(--base-size-8);
    font-size: var(--text-body-size-small);
    font-weight: 600;
    color: var(--fgColor-default);
    margin: 0;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    line-height: 1.6;
  }

  .folderDesc {
    font-size: var(--text-body-size-small);
    color: var(--fgColor-muted, #848d97);
    margin: 0;
    letter-spacing: 0.01em;
    text-transform: none;
    font-weight: 400;
  }

  .folderContent {
    display: flex;
    flex-direction: column;
  }

  .listItem {
    display: block;
    padding: 8px 0;
    text-decoration: none;
    color: inherit;

    .folderGroup & {
      border: 1px solid var(--borderColor-muted, #30363d);
    }
  }

  .listItem:hover {
    text-decoration: none !important;
  }

  .protoHeader {
    appearance: none;
    border: none;
    background: none;
    border-radius: var(--base-size-6);
    width: 100%;
    text-align: left;
    cursor: pointer;
    color: inherit;
    padding: 8px 0;
  }

  .protoHeader[aria-expanded="true"] .cardBody {
    background-color: var(--bgColor-muted);
    border-radius: var(--base-size-8);
  }

  .cardBody {
    padding: 12px 16px;
  }

  .cardBody:hover {
    background-color: var(--bgColor-muted);
    border-radius: var(--base-size-8);
  }

  .protoName {
    font-size: var(--text-title-size-medium);
    font-weight: 400;
    color: var(--fgColor-default, #e6edf3);
    margin: 0;
    letter-spacing: -0.02em;
    line-height: 1.6;
    transition: font-style 0.15s ease;
  }

  .protoDesc {
    font-size: 13px;
    color: var(--fgColor-muted, #848d97);
    margin: 4px 0 0;
    letter-spacing: 0.01em;
  }

  .author {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 6px;
  }

  .authorAvatars {
    display: flex;
    flex-direction: row;
  }

  .authorAvatars:hover .authorAvatar:not(:first-child) {
    margin-left: -2px;
  }

  .authorAvatar {
    width: 24px;
    height: 24px;
    border-radius: 50%;
    margin-left: -8px;
    transition: margin-left 50ms linear;
    outline: 2px solid var(--bgColor-default, #0d1117);
    position: relative;
  }

  .authorAvatar:first-child {
    margin-left: 0;
  }


  .authorName {
    font-size: 13px;
    color: var(--fgColor-muted, #848d97);
    letter-spacing: 0.01em;
  }

  .authorPlain {
    font-size: 13px;
    color: var(--fgColor-muted);
    margin: 4px 0 0;
    letter-spacing: 0.01em;
  }

  .flowList {
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
  }

  .folderGroup .listItem,
  .flowItem {
    border: 1px solid var(--borderColor-muted);
    padding: 0;
  }

  .folderGroup .listItem:not(:first-child),
  .flowItem:not(:first-child) {
    margin-top: -1px;
  }

  .folderGroup .listItem:first-child,
  .flowItem:first-child {
    border-top-left-radius: var(--base-size-6);
    border-top-right-radius: var(--base-size-6);
  }

  .folderGroup .listItem:first-child {
    margin-top: var(--base-size-8)
  }

  .folderGroup .listItem:last-child,
  .flowItem:last-child {
    border-bottom-left-radius: var(--base-size-6);
    border-bottom-right-radius: var(--base-size-6);
  }

  .folderGroup .listItem:only-child,
  .flowItem:only-child {
    border-radius: var(--base-size-6);
  }

  .flowItem .protoName {
    font-size: var(--text-title-size-small);
    color: var(--fgColor-muted);
  }

  .flowDesc {
    font-size: 13px;
    color: var(--fgColor-muted, #848d97);
    margin: 4px 0 0;
    letter-spacing: 0.01em;
  }

  .thumbnail {
    aspect-ratio: 16 / 10;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    background: var(--bgColor-inset, #010409);

    --placeholder-bg: var(--bgColor-inset, #010409);
    --placeholder-grid: var(--borderColor-default, #30363d);
    --placeholder-accent: var(--fgColor-accent, #58a6ff);
    --placeholder-fg: var(--fgColor-default, #c9d1d9);
    --placeholder-muted: var(--fgColor-muted, #484f58);
  }

  .thumbnail :global(svg) {
    width: 100%;
    height: 100%;
  }

  .empty {
    text-align: center;
    padding: 80px 24px;
    color: var(--fgColor-muted, #848d97);
    font-size: 15px;
    max-width: 720px;
    margin: 0 auto;
  }
</style>

// packages/core/src/svelte-plugin-ui/components/Viewfinder.jsx
/**
 * Viewfinder — prototype index and flow dashboard.
 *
 * Full-page component that lists prototypes as expandable groups,
 * each showing its flows. Global flows (not belonging to any prototype)
 * appear as an "Other flows" group.
 *
 * Mounted via mountViewfinder() from the viewfinder plugin entry point.
 */

import React, { useState, useMemo, useEffect, useCallback } from 'react'
import { buildPrototypeIndex } from '../../viewfinder.js'
import { getLocal, setLocal } from '../../localStorage.js'
import { Icon } from './Icon.jsx'

const VIEW_MODE_KEY = 'viewfinder.viewMode'
const EXPANDED_KEY = 'viewfinder.expanded'

function loadExpanded() {
  const raw = getLocal(EXPANDED_KEY)
  if (!raw) return {}
  try { return JSON.parse(raw) } catch { return {} }
}

function formatName(name) {
  return name
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function placeholderSvg(name) {
  const h = (function hashStr(s) {
    let v = 0
    for (let i = 0; i < s.length; i++) v = ((v << 5) - v + s.charCodeAt(i)) | 0
    return Math.abs(v)
  })(name)

  let rects = ''
  for (let i = 0; i < 12; i++) {
    const s = h * (i + 1)
    const x = (s * 7 + i * 31) % 320
    const y = (s * 13 + i * 17) % 200
    const w = 20 + (s * (i + 3)) % 80
    const ht = 8 + (s * (i + 7)) % 40
    const opacity = 0.06 + ((s * (i + 2)) % 20) / 100
    const fill = i % 3 === 0 ? 'var(--sb--placeholder-accent)' : i % 3 === 1 ? 'var(--sb--placeholder-fg)' : 'var(--sb--placeholder-muted)'
    rects += `<rect x="${x}" y="${y}" width="${w}" height="${ht}" rx="2" fill="${fill}" opacity="${opacity}" />`
  }

  let lines = ''
  for (let i = 0; i < 6; i++) {
    const s = h * (i + 5)
    const y = 10 + (s % 180)
    lines += `<line x1="0" y1="${y}" x2="320" y2="${y}" stroke="var(--sb--placeholder-grid)" stroke-width="0.5" opacity="0.4" />`
  }
  for (let i = 0; i < 8; i++) {
    const s = h * (i + 9)
    const x = 10 + (s % 300)
    lines += `<line x1="${x}" y1="0" x2="${x}" y2="200" stroke="var(--sb--placeholder-grid)" stroke-width="0.5" opacity="0.3" />`
  }

  return `<svg viewBox="0 0 320 200" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><rect width="320" height="200" fill="var(--sb--placeholder-bg)" />${lines}${rects}</svg>`
}

/* ── Author block ── */
function AuthorBlock({ author, gitAuthor }) {
  if (author) {
    const authors = Array.isArray(author) ? author : [author]
    return (
      <div className="author">
        <span className="authorAvatars">
          {authors.map((a) => (
            <img key={a} src={`https://github.com/${a}.png?size=48`} alt={a} className="authorAvatar" />
          ))}
        </span>
        <span className="authorName">{authors.join(', ')}</span>
      </div>
    )
  }
  if (gitAuthor) {
    return <p className="authorPlain">{gitAuthor}</p>
  }
  return null
}

/* ── Proto entry ── */
function ProtoEntry({ proto, isExpanded, toggle, withBase, showThumbnails }) {
  if (proto.isExternal) {
    return (
      <section className="protoGroup">
        <a className="listItem" href={proto.externalUrl} target="_blank" rel="noopener noreferrer">
          <div className="cardBody">
            <p className="protoName">
              {proto.icon && <span className="protoIcon">{proto.icon}</span>}
              {proto.name}
              <span className="externalBadge">
                <Icon size={12} color="var(--fgColor-muted)" name="primer/link-external" offsetY={-2} />
                external
              </span>
            </p>
            {proto.description && <p className="protoDesc">{proto.description}</p>}
            <AuthorBlock author={proto.author} gitAuthor={proto.gitAuthor} />
          </div>
        </a>
      </section>
    )
  }

  if (proto.hideFlows && proto.flows.length === 1) {
    return (
      <section className="protoGroup">
        <a className="listItem" href={withBase(proto.flows[0].route)}>
          <div className="cardBody">
            <p className={`protoName${proto.dirName === '__global__' ? ' otherflows' : ''}`}>
              {proto.icon && <span className="protoIcon">{proto.icon}</span>}
              {proto.name}
            </p>
            {proto.description && <p className="protoDesc">{proto.description}</p>}
            <AuthorBlock author={proto.author} gitAuthor={proto.gitAuthor} />
          </div>
        </a>
      </section>
    )
  }

  if (proto.flows.length > 0) {
    const expanded = isExpanded(proto.dirName)
    return (
      <section className="protoGroup">
        <button
          className="listItem protoHeader"
          onClick={() => toggle(proto.dirName)}
          aria-expanded={expanded}
        >
          <div className="cardBody">
            <p className={`protoName${proto.dirName === '__global__' ? ' otherflows' : ''}`}>
              {proto.icon && <span className="protoIcon">{proto.icon}</span>}
              {proto.name}
              <span className="protoChevron">
                {expanded
                  ? <Icon size={12} color="var(--fgColor-disabled)" name="primer/chevron-down" offsetY={-3} offsetX={2} />
                  : <Icon size={12} color="var(--fgColor-disabled)" name="primer/chevron-right" offsetY={-3} offsetX={2} />
                }
              </span>
            </p>
            {proto.description && <p className="protoDesc">{proto.description}</p>}
            <AuthorBlock author={proto.author} gitAuthor={proto.gitAuthor} />
          </div>
        </button>

        {!(proto.hideFlows && proto.flows.length === 1) && expanded && proto.flows.length > 0 && (
          <div className="flowList">
            {proto.flows.map((flow) => (
              <a key={flow.key} href={withBase(flow.route)} className="listItem flowItem">
                {showThumbnails && (
                  <div className="thumbnail" dangerouslySetInnerHTML={{ __html: placeholderSvg(flow.key) }} />
                )}
                <div className="cardBody">
                  <p className="protoName">{flow.meta?.title || formatName(flow.name)}</p>
                  {flow.meta?.description && <p className="flowDesc">{flow.meta.description}</p>}
                </div>
              </a>
            ))}
          </div>
        )}
      </section>
    )
  }

  // Prototype with no flows — navigates directly
  return (
    <section className="protoGroup">
      <a className="listItem" href={withBase(`/${proto.dirName}`)}>
        <div className="cardBody">
          <p className={`protoName${proto.dirName === '__global__' ? ' otherflows' : ''}`}>
            {proto.icon && <span className="protoIcon">{proto.icon}</span>}
            {proto.name}
          </p>
          {proto.description && <p className="protoDesc">{proto.description}</p>}
          <AuthorBlock author={proto.author} gitAuthor={proto.gitAuthor} />
        </div>
      </a>
    </section>
  )
}

/* ── Canvas entry ── */
function CanvasEntry({ canvas, withBase }) {
  const authors = canvas.author
    ? (Array.isArray(canvas.author) ? canvas.author : [canvas.author])
    : null

  return (
    <section className="protoGroup">
      <a className="listItem" href={withBase(canvas.route)}>
        <div className="cardBody">
          <p className="protoName">
            <span className="protoIcon">{canvas.icon || ''}</span>
            {canvas.name}
          </p>
          {canvas.description && <p className="protoDesc">{canvas.description}</p>}
          {authors ? (
            <div className="author">
              <span className="authorAvatars">
                {authors.map((a) => (
                  <img key={a} src={`https://github.com/${a}.png?size=48`} alt={a} className="authorAvatar" />
                ))}
              </span>
              <span className="authorName">{authors.join(', ')}</span>
            </div>
          ) : canvas.gitAuthor ? (
            <p className="authorPlain">{canvas.gitAuthor}</p>
          ) : null}
        </div>
      </a>
    </section>
  )
}

/* ── Folder section ── */
function FolderSection({ folder, isExpanded, toggle, renderItems, itemKey = 'prototypes' }) {
  const key = `folder:${folder.dirName}`
  const expanded = isExpanded(key)
  const items = folder[itemKey] || []

  return (
    <section className={`folderGroup${expanded ? ' folderGroupOpen' : ''}`}>
      <button
        className="folderHeader"
        onClick={() => toggle(key)}
        aria-expanded={expanded}
      >
        <p className="folderName">
          <span>
            {expanded
              ? <Icon size={20} offsetY={-1.5} name="folder-open" color="#54aeff" />
              : <Icon size={20} offsetY={-1.5} name="folder" color="#54aeff" />
            }
          </span>
          {folder.name}
        </p>
        {folder.description && <p className="folderDesc">{folder.description}</p>}
      </button>
      {expanded && items.length > 0 && (
        <div className="folderContent">
          {renderItems(items)}
        </div>
      )}
    </section>
  )
}

/* ── Main Viewfinder component ── */
export function Viewfinder({
  title = 'Storyboard',
  subtitle = '',
  basePath = '/',
  knownRoutes = [],
  showThumbnails = false,
  hideDefaultFlow = false,
}) {
  const prototypeIndex = useMemo(() => buildPrototypeIndex(knownRoutes), [knownRoutes])

  const globalFlows = useMemo(() => {
    return hideDefaultFlow
      ? prototypeIndex.globalFlows.filter((f) => f.key !== 'default')
      : prototypeIndex.globalFlows
  }, [prototypeIndex, hideDefaultFlow])

  const ungroupedProtos = prototypeIndex.prototypes
  const folders = prototypeIndex.folders || []

  const otherFlows = useMemo(() => {
    if (globalFlows.length === 0) return null
    return {
      name: 'Other flows',
      dirName: '__global__',
      description: null,
      author: null,
      gitAuthor: null,
      lastModified: null,
      icon: null,
      team: null,
      tags: null,
      flows: globalFlows,
    }
  }, [globalFlows])

  const totalProtos = ungroupedProtos.length + folders.reduce((sum, f) => sum + f.prototypes.length, 0)

  // Sorting
  const [sortBy, setSortBy] = useState('updated')
  const sortedProtos = prototypeIndex.sorted?.[sortBy]?.prototypes ?? ungroupedProtos
  const sortedFolders = prototypeIndex.sorted?.[sortBy]?.folders ?? folders

  // Canvases
  const ungroupedCanvases = prototypeIndex.canvases || []
  const sortedCanvases = prototypeIndex.sorted?.[sortBy]?.canvases ?? ungroupedCanvases
  const totalCanvases = ungroupedCanvases.length + folders.reduce((sum, f) => sum + (f.canvases?.length || 0), 0)

  // View mode
  const [viewMode, setViewMode] = useState(() =>
    getLocal(VIEW_MODE_KEY) === 'canvases' ? 'canvases' : 'prototypes'
  )

  useEffect(() => {
    setLocal(VIEW_MODE_KEY, viewMode)
  }, [viewMode])

  // Canvas folders
  const canvasFolders = useMemo(() => {
    const src = prototypeIndex.sorted?.[sortBy]?.folders ?? folders
    return src
      .filter((f) => f.canvases && f.canvases.length > 0)
      .map((f) => ({ ...f, prototypes: [], canvases: f.canvases }))
  }, [prototypeIndex, sortBy, folders])

  // Proto-only folders
  const protoOnlyFolders = useMemo(() => {
    const src = prototypeIndex.sorted?.[sortBy]?.folders ?? folders
    return src
      .filter((f) => f.prototypes.length > 0)
      .map((f) => ({ ...f, canvases: [] }))
  }, [prototypeIndex, sortBy, folders])

  // Expanded state
  const [expanded, setExpanded] = useState(loadExpanded)

  const isExpandedFn = useCallback((dirName) => expanded[dirName] ?? false, [expanded])

  const toggleFn = useCallback((dirName) => {
    setExpanded((prev) => {
      const next = { ...prev, [dirName]: !(prev[dirName] ?? false) }
      setLocal(EXPANDED_KEY, JSON.stringify(next))
      return next
    })
  }, [])

  // URL helpers
  const withBase = useCallback((route) => {
    const normalizedRoute = route.startsWith('/') ? route : `/${route}`
    const normalizedBase = (basePath || '/').replace(/\/+$/, '')
    if (!normalizedBase || normalizedBase === '/') return normalizedRoute
    return `${normalizedBase}${normalizedRoute}`.replace(/\/+/g, '/')
  }, [basePath])

  // Branch switching
  const branches = (typeof window !== 'undefined' && Array.isArray(window.__SB_BRANCHES__))
    ? window.__SB_BRANCHES__
    : null

  const branchBasePath = (basePath || '/storyboard-source/').replace(/\/branch--[^/]*\/$/, '/')
  const currentBranch = useMemo(() => {
    const m = (basePath || '').match(/\/branch--([^/]+)\/?$/)
    return m ? m[1] : 'main'
  }, [basePath])

  function handleBranchChange(e) {
    const folder = e.target.value
    if (folder) {
      window.location.href = `${branchBasePath}${folder}/`
    }
  }

  return (
    <div className="container">
      <header className="header">
        <div className="headerTop">
          <div>
            <h1 className="title">{title}</h1>
            {subtitle && <p className="subtitle">{subtitle}</p>}
          </div>
        </div>
        <div className="controlsRow">
          {/* View mode toggle */}
          <div className="sortToggle">
            <button
              className={`sortButton${viewMode === 'prototypes' ? ' sortButtonActive' : ''}`}
              onClick={() => setViewMode('prototypes')}
            >
              Prototypes
            </button>
            <button
              className={`sortButton${viewMode === 'canvases' ? ' sortButtonActive' : ''}`}
              onClick={() => setViewMode('canvases')}
            >
              Canvas
            </button>
          </div>
          {/* Sort toggle — hidden for now */}
          <div className="sortToggle" style={{ display: 'none' }}>
            <button
              className={`sortButton${sortBy === 'updated' ? ' sortButtonActive' : ''}`}
              onClick={() => setSortBy('updated')}
            >
              <Icon name="primer/clock" size={14} color="var(--fgColor-muted)" />
              Last updated
            </button>
            <button
              className={`sortButton${sortBy === 'title' ? ' sortButtonActive' : ''}`}
              onClick={() => setSortBy('title')}
            >
              <Icon name="primer/sort-asc" size={14} color="var(--fgColor-muted)" />
              Title A–Z
            </button>
          </div>
          {branches && branches.length > 0 && (
            <div className="branchDropdown">
              <span className="branchIcon">
                <Icon size={16} color="var(--fgColor-muted)" offsetY={-1} offsetX={2} name="primer/git-branch" />
              </span>
              <select
                className="branchSelect"
                onChange={handleBranchChange}
                aria-label="Switch branch"
                defaultValue=""
              >
                <option value="" disabled>{currentBranch}</option>
                {branches.map((b) => (
                  <option key={b.folder} value={b.folder}>{b.branch}</option>
                ))}
              </select>
            </div>
          )}
        </div>
      </header>

      {viewMode === 'prototypes' && totalProtos === 0 && folders.length === 0 ? (
        <p className="empty">No flows found. Add a <code>*.flow.json</code> file to get started.</p>
      ) : viewMode === 'canvases' && totalCanvases === 0 ? (
        <p className="empty">No canvases found. Add a <code>*.canvas.jsonl</code> file to get started.</p>
      ) : (
        <div className="list">
          {viewMode === 'prototypes' ? (
            <>
              {protoOnlyFolders.map((folder) => (
                <FolderSection
                  key={folder.dirName}
                  folder={folder}
                  isExpanded={isExpandedFn}
                  toggle={toggleFn}
                  renderItems={(protos) =>
                    protos.map((proto) => (
                      <ProtoEntry
                        key={proto.dirName}
                        proto={proto}
                        isExpanded={isExpandedFn}
                        toggle={toggleFn}
                        withBase={withBase}
                        showThumbnails={showThumbnails}
                      />
                    ))
                  }
                />
              ))}

              {sortedProtos.map((proto) => (
                <ProtoEntry
                  key={proto.dirName}
                  proto={proto}
                  isExpanded={isExpandedFn}
                  toggle={toggleFn}
                  withBase={withBase}
                  showThumbnails={showThumbnails}
                />
              ))}

              {otherFlows && (
                <ProtoEntry
                  proto={otherFlows}
                  isExpanded={isExpandedFn}
                  toggle={toggleFn}
                  withBase={withBase}
                  showThumbnails={showThumbnails}
                />
              )}
            </>
          ) : (
            <>
              <div className="canvasWarning">
                <Icon size={14} name="primer/alert" color="#9a6700" offsetY={-1} />
                <span>Canvas is an experimental feature. Use with caution.</span>
              </div>
              {canvasFolders.map((folder) => (
                <FolderSection
                  key={folder.dirName}
                  folder={folder}
                  isExpanded={isExpandedFn}
                  toggle={toggleFn}
                  itemKey="canvases"
                  renderItems={(canvases) =>
                    canvases.map((canvas) => (
                      <CanvasEntry key={canvas.dirName} canvas={canvas} withBase={withBase} />
                    ))
                  }
                />
              ))}

              {sortedCanvases.map((canvas) => (
                <CanvasEntry key={canvas.dirName} canvas={canvas} withBase={withBase} />
              ))}
            </>
          )}
        </div>
      )}
    </div>
  )
}

export default Viewfinder
