// packages/core/src/comments/ui/AuthModal.svelte
<!--
  AuthModal — PAT entry modal for comments authentication.
  Uses shadcn Button, Input, Label, Alert, Avatar.
-->

<script lang="ts">
  import { onMount } from 'svelte'
  import { setToken, validateToken } from '../auth.js'
  import { getCommentsConfig } from '../config.js'
  import { Button } from '../../lib/components/ui/button/index.js'
  import { Input } from '../../lib/components/ui/input/index.js'
  import { Label } from '../../lib/components/ui/label/index.js'
  import * as Alert from '../../lib/components/ui/alert/index.js'
  import * as Avatar from '../../lib/components/ui/avatar/index.js'

  interface Props {
    onDone?: (user: { login: string; avatarUrl: string }) => void
    onClose?: () => void
    initialError?: string | null
  }

  let { onDone, onClose, initialError = null }: Props = $props()

  let token = $state('')
  let submitting = $state(false)
  let error: string | null = $state(null)
  let user: { login: string; avatarUrl: string } | null = $state(null)
  let inputEl: HTMLInputElement | null = $state(null)
  const commentsConfig = getCommentsConfig()
  const repoOwner = commentsConfig?.repo?.owner || 'github'
  const repoName = commentsConfig?.repo?.name || 'storyboard'
  const repoSlug = `${repoOwner}/${repoName}`
  const tokenTemplateName = 'Storyboard Comments'
  const tokenTemplateDescription =
    `Token for enabling comments on ${repoSlug} prototype. Configure as:\n\n` +
    `Owner: ${repoOwner}\n` +
    'Expiration: 366 days (recommended)\n' +
    `Repository access: Only select repositories > ${repoSlug}\n` +
    'Permissions: Repositories > Discussions > Access: Read and Write'
  const tokenCreateUrl =
    `https://github.com/settings/personal-access-tokens/new?` +
    new URLSearchParams({
      name: tokenTemplateName,
      description: tokenTemplateDescription,
    }).toString()

  onMount(() => {
    error = initialError
    inputEl?.focus()
  })

  async function submit() {
    const val = token.trim()
    if (!val) return
    submitting = true; error = null
    try { const result = await validateToken(val); setToken(val); user = result }
    catch (err: any) { error = err.message }
    finally { submitting = false }
  }

  function done() { if (user) onDone?.(user) }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !user) submit()
  }
</script>

<div class="bg-popover text-popover-foreground border border-border rounded-lg shadow-lg overflow-hidden max-w-[600px] w-full font-sans">
  <div class="flex items-center justify-between px-4 py-3 border-b border-border">
    <h2 class="text-medium font-semibold">Sign in for comments</h2>
    <Button variant="ghost" size="icon" onclick={onClose} aria-label="Close" class="h-7 w-7 text-muted-foreground">&#215;</Button>
  </div>
  <div class="p-4 space-y-3">
    {#if error}<Alert.Root variant="destructive"><Alert.Description>{error}</Alert.Description></Alert.Root>{/if}
    <p class="text-sm text-muted-foreground leading-relaxed">
      Leave comments for other users to see and respond, and react to! Storyboard comments use Discussions as a back-end and require a GitHub PAT to be enabled.
    </p>
    <p class="text-sm text-muted-foreground leading-relaxed">
      Create a <a class="text-primary underline" href={tokenCreateUrl} target="_blank" rel="noopener">GitHub Fine-Grained Personal Access Token</a> with the settings below to get started:
    </p>
    <div class="px-3 py-2 bg-muted border border-border rounded text-xs text-muted-foreground leading-relaxed">
      <div class="mb-1"><strong class="text-foreground">Fine-grained Personal Access Token</strong></div>
      <div>Owner: <code class="px-1 bg-background rounded font-mono text-foreground">{repoOwner}</code></div>
      <div>Expiration: <code class="px-1 bg-background rounded font-mono text-foreground">366 days</code> (recommended)</div>
      <div>Repository access: <code class="px-1 bg-background rounded font-mono text-foreground">Only select repositories &gt; {repoSlug}</code></div>
      <div>Permissions: <code class="px-1 bg-background rounded font-mono text-foreground">Repositories > Discussions > Access: Read and Write</code></div>
    </div>
    <div class="space-y-1">
      <Label for="sb-auth-token-input">Personal Access Token</Label>
      <Input id="sb-auth-token-input" type="password" placeholder="github_pat_\u2026 or ghp_\u2026" autocomplete="off" spellcheck="false" class="font-mono" bind:value={token} bind:ref={inputEl} onkeydown={handleKeydown} />
    </div>
    {#if user}
      <div class="flex items-center py-1 gap-3">
        <Avatar.Root class="h-10 w-10"><Avatar.Image src={user.avatarUrl} alt={user.login} /><Avatar.Fallback>{user.login[0]?.toUpperCase()}</Avatar.Fallback></Avatar.Root>
        <div class="text-sm"><span class="text-foreground">{user.login}</span><span class="block text-xs text-success mt-0.5">&#10003; Signed in</span></div>
      </div>
    {/if}
    <Alert.Root variant="warning" class="bg-amber-100 border-amber-300">
      <Alert.Description class="text-amber-700">
        ⚠️ Comments are an experimental feature and may be unstable.
      </Alert.Description>
    </Alert.Root>    
  </div>
  <div class="flex items-center justify-end px-4 py-3 border-t border-border gap-2">
    <Button variant="outline" size="sm" onclick={onClose}>Cancel</Button>
    <Button size="sm" disabled={submitting} onclick={user ? done : submit}>{user ? 'Done' : (submitting ? 'Validating\u2026' : 'Sign in')}</Button>
  </div>
</div>

// packages/react/src/AuthModal/AuthModal.jsx
/**
 * AuthModal — Global PAT entry dialog for comments authentication.
 * Mounted at app root, triggered by:
 *   - Svelte CoreUIBar (comments tool / "C" shortcut) via 'storyboard:open-auth-modal' event
 *   - ViewfinderNew sidebar login button via same event
 */
import { useState, useEffect, useCallback } from 'react'
import { Dialog } from '@base-ui/react/dialog'
import css from './AuthModal.module.css'

const COMMENTS_TOKEN_KEY = 'sb-comments-token'

function getRepoInfo() {
  try {
    // eslint-disable-next-line no-undef
    const cfg = typeof __STORYBOARD_CONFIG__ !== 'undefined' ? __STORYBOARD_CONFIG__ : null
    const repo = cfg?.repository
    if (repo?.owner && repo?.name) return repo
  } catch { /* ignore */ }
  return { owner: 'github', name: 'storyboard' }
}

export default function AuthModal() {
  const [open, setOpen] = useState(false)
  const [tokenValue, setTokenValue] = useState('')

  useEffect(() => {
    function handleOpen() { setOpen(true) }
    document.addEventListener('storyboard:open-auth-modal', handleOpen)
    return () => document.removeEventListener('storyboard:open-auth-modal', handleOpen)
  }, [])

  const handleSignIn = useCallback(() => {
    const trimmed = tokenValue.trim()
    if (!trimmed) return

    try { localStorage.setItem(COMMENTS_TOKEN_KEY, trimmed) } catch { /* ignore */ }

    try {
      import('@dfosco/storyboard-core/comments').then(({ setToken, validateToken }) => {
        setToken(trimmed)
        // Validate to cache user info (login + avatar), then notify Viewfinder
        validateToken(trimmed)
          .then(() => document.dispatchEvent(new CustomEvent('storyboard:auth-changed')))
          .catch(() => document.dispatchEvent(new CustomEvent('storyboard:auth-changed')))
      }).catch(() => {})
    } catch { /* comments module may not be initialized */ }

    setTokenValue('')
    setOpen(false)
  }, [tokenValue])

  const handleKeyDown = useCallback((e) => {
    if (e.key === 'Enter') handleSignIn()
  }, [handleSignIn])

  const repo = getRepoInfo()

  return (
    <Dialog.Root open={open} onOpenChange={setOpen}>
      <Dialog.Portal>
        <Dialog.Backdrop className={css.backdrop} />
        <div className={css.popupWrap}>
          <Dialog.Popup className={css.popup}>
            <Dialog.Title className={css.title}>Sign in with GitHub</Dialog.Title>
            <Dialog.Description className={css.desc}>
              Leave comments for other users to see and respond, and react to! Storyboard
              comments use Discussions as a back-end and require a GitHub PAT to be enabled.
            </Dialog.Description>
            <Dialog.Close className={css.closeBtn} aria-label="Close">×</Dialog.Close>

            <hr className={css.separator} />

            <div className={css.tokenCard}>
              <p className={css.tokenCardTitle}>Fine-grained Personal Access Token</p>
              <div className={css.tokenCardRow}>
                <span className={css.tokenCardLabel}>Owner:</span>
                <code className={css.tokenCardCode}>{repo.owner}</code>
              </div>
              <div className={css.tokenCardRow}>
                <span className={css.tokenCardLabel}>Expiration:</span>
                <code className={css.tokenCardCode}>366 days</code>
                <span className={css.tokenCardHint}>(recommended)</span>
              </div>
              <div className={css.tokenCardRow}>
                <span className={css.tokenCardLabel}>Repository access:</span>
                <code className={css.tokenCardCode}>Only select repositories &gt; {repo.owner}/{repo.name}</code>
              </div>
              <div className={css.tokenCardRow}>
                <span className={css.tokenCardLabel}>Permissions:</span>
                <code className={css.tokenCardCode}>Repositories &gt; Discussions &gt; Access: Read and Write</code>
              </div>
            </div>

            <a
              className={css.tokenLink}
              href="https://github.com/settings/personal-access-tokens/new"
              target="_blank"
              rel="noopener noreferrer"
            >
              Create a GitHub Fine-Grained Personal Access Token ↗
            </a>

            <hr className={css.separator} />

            <label className={css.label} htmlFor="auth-modal-token">Personal Access Token</label>
            <input
              id="auth-modal-token"
              className={css.input}
              placeholder="github_pat_… or ghp_…"
              type="password"
              autoFocus
              value={tokenValue}
              onChange={e => setTokenValue(e.target.value)}
              onKeyDown={handleKeyDown}
            />

            <div className={css.warning}>
              <span className={css.warningIcon}>⚠️</span>
              <span>Comments are an experimental feature and may be unstable.</span>
            </div>

            <div className={css.actions}>
              <Dialog.Close className={css.btnSecondary}>Cancel</Dialog.Close>
              <button className={css.btnPrimary} onClick={handleSignIn}>Sign in</button>
            </div>
          </Dialog.Popup>
        </div>
      </Dialog.Portal>
    </Dialog.Root>
  )
}
